### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by adnannidal** [inspireui/mstore#1]
only 2-3 images are showing.

Login/Signup showing loader only no progress.

How can I configure FB login?

Username: adnannidal

**Comment by inspireui** [comment]
Hi, could you download the repos Wordpress here for the installing or have a check to some the mandatory config from this document - https://mstore.gitbooks.io/mstore-manual/content/pro-version/wordpress-installing.html

**Comment by irsanrml** [comment]
Hello @inspireui, 

how can i login to wp-admin page using root username?
here is users wp default : 

![image](https://user-images.githubusercontent.com/4324813/27847802-3c9f8f80-616a-11e7-9eec-e5ff5fc291df.png)

i don't know the password, please let me know

my username : irsanrml

**Comment by inspireui** [comment]
Hi, please use: root / 12345678 or user / 12345678
