### ISSUE TITLE
error with install

### ISSUE THREAD

**Issue by Fansis** [inspireui/mstore#10]
hi there,
i try to setup but this is come up with this error. please check and let me know how to fix this thanks
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by inspireui** [comment]
Could i know your Window or Mac? One solution for Dex issue is updated the Android SDK to latest one, and like this config - https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 are fixed this installing issues. Please help to open new ticket if there are still issues. Thank you so much for your feedback
