### ISSUE TITLE
react/rcteventemitter.h' file not found

### ISSUE THREAD

**Issue by joelbertlive** [inspireui/mstore#100]
Please see attached image
<img width="1280" alt="screen shot 2017-12-13 at 9 19 32 pm" src="https://user-images.githubusercontent.com/5482265/33976676-7d7ee5cc-e04b-11e7-85ba-abd2971ed030.png">

**Comment by inspireui** [comment]
Could you check the solution from this guide - https://mstore.gitbooks.io/mstore-manual/content/chapter7.html

**Comment by minhcasi** [comment]
Hi, feel free to reopen this ticket if you still have a issues. Thank you!
