### ISSUE TITLE
App stays "LOADING..." when I choose "Cash on delivery"

### ISSUE THREAD

**Issue by SantiMancini** [inspireui/mstore#101]
Any solutions to this issue? I can't test the whole App.

![paymenterror](https://user-images.githubusercontent.com/21128914/33993637-22209f48-e0b6-11e7-8abb-0c2164dc28b4.PNG)

**Comment by inspireui** [comment]
You can use Reactotron to check the URL return issue at the confirm order to find out the problem – https://mstore.gitbooks.io/mstore-manual/content/chapter2.html

Could you send us the response json after tap to the COD option. Thank you!

**Comment by karim-aly** [comment]
I was having the same issue.
billing fields for my user was all blank.
I set them from the wp admin and it worked.

@inspireui this issue is due to the way signup works in the app, please fix this issue.

**Comment by inspireui** [comment]
Hi @karim-aly, it will be fixed on next version v3.4.3 which will be available on next 1-2 days. Thank you!

**Comment by minhcasi** [comment]
Hi @SantiMancini @karim-aly could you help to check if this issue is resolved on v3.4.3 so that we can close the ticket. Thank you!

**Comment by SantiMancini** [comment]
I tried ordering with you app credentials and managed to get past the 'LOADING' issue. Then, I tried with my own Woocommerce instance, and when I try to Log In or Sign Up, I get a toast error saying <Unknow controll 'mstore_user'>. So, I'm not sure if this is fixed at all.

**Comment by inspireui** [comment]
Hi @SantiMancini have you tried to enable the Mstore-checkout from the Json Controller, please have a look to the screenshot on this guide - https://mstore.gitbooks.io/mstore-manual/content/pro-version/wordpress-installing.html

**Comment by SantiMancini** [comment]
Hi @inspireui that was it! Configured again my  Wordpress instance a I was able to submit an order via cash on delivery. Thank you guys! I'll let you know if I have any other issue.

By the way, product description is still buggy, it renders outside of the emulator screen. I already tried using the new index.js in /containers/Details. I'll wait for your comments.

Thanks again!

1.
