### ISSUE TITLE
iOS  project build failes

### ISSUE THREAD

**Issue by karim-aly** [inspireui/mstore#102]
Error when building iOS project using latest update v3.4.2
When using Xcode:

`/Users/karimaly/ReactNativeWorkspace/Kamkilo/node_modules/react-native/Libraries/Text/RCTShadowText.m:201:38: Property 'layoutDirection' not found on object of type 'RCTShadowText *'`

When using react-native run-iso:

> /Users/karimaly/ReactNativeWorkspace/Kamkilo/node_modules/react-native-linear-gradient/BVLinearGradient/BVLinearGradientManager.h:1:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

> ** BUILD FAILED **

> The following commands produced analyzer issues:
	Analyze /Users/karimaly/ReactNativeWorkspace/Kamkilo/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/karimaly/ReactNativeWorkspace/Kamkilo/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

> The following build commands failed:
	CompileC /Users/karimaly/ReactNativeWorkspace/Kamkilo/ios/build/Build/Intermediates.noindex/BVLinearGradient.build/Debug-iphonesimulator/BVLinearGradient.build/Objects-normal/x86_64/BVLinearGradientManager.o BVLinearGradient/BVLinearGradientManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

> Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
lstat of /Users/karimaly/ReactNativeWorkspace/Kamkilo/ios/build/Build/Products/Debug-iphonesimulator/beostore.app failed: No such file or directory
No such file or directory
Print: Entry, ":CFBundleIdentifier", Does Not Exist

> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by inspireui** [comment]
Hi, please use this solution for the fix - https://mstore.gitbooks.io/mstore-manual/content/chapter7.html

**Comment by karim-aly** [comment]
Ok, I'll try the fix.

**Comment by mtx62** [comment]
Greetings,
I'm facing the same error even though I tried the solutions in the document:
https://mstore.gitbooks.io/mstore-manual/chapter7.html
but still I can't start the app

**Comment by karim-aly** [comment]
For me adding React to the Build in Project Schemes fixed the problem.

**Comment by inspireui** [comment]
@mtx62 could you share your screenshot when edit schema, and the detail log warning from XCode. Thank you!

**Comment by mtx62** [comment]
Dear @inspireui it's working now,
The problem was that I was selecting beostore-tvOS and I did the configuration and it's not working,
But when I select beostore and I did the configuration it's working now.
Thank you.

**Comment by inspireui** [comment]
Great @mtx62 thank for confirm
