### ISSUE TITLE
branding not working

### ISSUE THREAD

**Issue by blueprin4** [inspireui/mstore#103]
I followed your instructions on branding and it stills says mstore with your logo.

**Comment by blueprin4** [comment]
also i tried this and still get same error: react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --sourcemap-output android/app/src/main/assets/index.android.map --assets-dest android/app/src/main/res/

**Comment by inspireui** [comment]
Hi, could you take the screenshot to show us which the logo that you have changed?
