### ISSUE TITLE
Splash Screen don't show anymore on Android

### ISSUE THREAD

**Issue by karim-aly** [inspireui/mstore#104]
After upgrade to V3.4.2, Splash Screen don't show anymore on Android.

**Comment by eric90066** [comment]
I see the same.

**Comment by minhcasi** [comment]
We are checking this issue and get back to you later

**Comment by SantiMancini** [comment]
+1

Also, I get a blank page when I select'Contact Us' in sidebar, and nothing happens when I select 'News'. This errors are happening with this new update, as well as the description issue.

**Comment by karim-aly** [comment]
@SantiMancini +1 for the product description

**Comment by shweta-bavishi** [comment]
Any update on this? We are facing the same issue

**Comment by inspireui** [comment]
Hi, i've updated as a bug for next v3.4.5 release. Thank you!

**Comment by shweta-bavishi** [comment]
Facing the same issue. I have added the url in Config.js file.
`WebPages: {Marketing: 'https://smartify.in/contact-us/'}`

The custom pages are working perfectly fine for iOS devices, but showing blank pages for android devices

**Comment by andybedoy** [comment]
what happend with this error?

**Comment by inspireui** [comment]
pls download the latest version 3.4.5 will be fixed this issues - thank you!
