### ISSUE TITLE
import demo sql error

### ISSUE THREAD

**Issue by basechain** [inspireui/mstore#105]
I use MySQL 5.7
There is an error in importing data：
ERROR 1067 (42000): Invalid default value for 'comment_date'
ERROR 1067 (42000): Invalid default value for 'link_updated'
ERROR 1067 (42000): Invalid default value for 'post_date'
ERROR 1067 (42000): Invalid default value for 'user_registered'
ERROR 1067 (42000): Invalid default value for 'access_granted'
ERROR 1146 (42S02): Table 'mstore.wp_comments' doesn't exist
ERROR 1146 (42S02): Table 'mstore.wp_posts' doesn't exist
ERROR 1146 (42S02): Table 'mstore.wp_users' doesn't exist

**Comment by minhcasi** [comment]
Could you try to use PhpMyAdmin to import it. Thank you!

**Comment by basechain** [comment]
replace the "0000-00-00 00:00:00" to "2017-01-01 01:01:01"  is OK

**Comment by inspireui** [comment]
Great, please for your confirm.
