### ISSUE TITLE
disable fullscreen mode

### ISSUE THREAD

**Issue by mgolkardev** [inspireui/mstore#106]
Hi
How can I disable full screen mode in android?

![ppppppppppppp](https://user-images.githubusercontent.com/4500080/34179031-909680ac-e51e-11e7-8a4b-3d6b0dcfa992.png)

Thanks

**Comment by inspireui** [comment]
Hi, there is the option showStatusBar to disable the status bar form the config.js file, could you have a check if it is fixed on Android.

**Comment by mgolkardev** [comment]
Thank you
