### ISSUE TITLE
Can't create a new user (Signup) after upgrading to V3.4.3

### ISSUE THREAD

**Issue by karim-aly** [inspireui/mstore#108]
@inspireui After upgrading to V3.4.3, I can't create a new user.
A toast pops with this message:

> Invalid access, unverifiable 'nonce' value. Use the 'get_nonce' Core API Method.

**Comment by mezzat11** [comment]
Same problem here

**Comment by MechEight** [comment]
Same here

**Comment by inspireui** [comment]
Hi, i've updated it as bug and will update new version very soon on next couple of days. Thank you!

**Comment by mezzat11** [comment]
thank you .. don't forget shipping selection ( cann't unselect free
shipping )  bug

**Comment by martinledjo** [comment]
Error on 3.4.4 "Hello undefined" after signup no account create
