### ISSUE TITLE
Can't login inside app

### ISSUE THREAD

**Issue by MechEight** [inspireui/mstore#109]
When I try to login inside the app I get an error in the ios simulator

![simulator screen shot - iphone 6 - 2017-12-26 at 23 14 59](https://user-images.githubusercontent.com/24413827/34365733-e522e802-ea93-11e7-8156-323533ce8b77.png)

In Reactotron I can see this request being made:
http://local.wordpress.test/api/mstore_user/generate_auth_cookie/?second=120960000000&username=admin&password=password&insecure=cool

The response seems to be the problem I think, there is a HTML error before the JSON:
```
<br />
<b>Notice</b>:  WP_Date_Query was called <strong>incorrectly</strong>. Invalid value <code>120960000000</code> for <code>second</code>. Expected value should be between <code>0</code> and <code>59</code>. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.1.0.) in <b>/srv/www/wordpress-default/public_html/wp-includes/functions.php</b> on line <b>4146</b><br />
{"status":"ok","cookie":"admin|1515536174|0fUvEonhP0KsddUBvCHFOktIoHGFI7Ji9vXhi6c55nw|b505be925c6bc5d908682672ba22b89248928d085f77d7bd0d8c53b4dec7a2e9","cookie_name":"wordpress_logged_in_4a5a5e3d7105ef3340c871f81e74ac36","user":{"id":1,"username":"admin","nicename":"admin","email":"admin@local.test","url":"","registered":"2017-12-12 22:02:22","displayname":"admin","firstname":"A","lastname":"B","nickname":"admin","description":"","capabilities":{"administrator":true},"avatar":null}}
```

**Comment by inspireui** [comment]
Hi, thank you, this will be fix on next v3.4.4

**Comment by MechEight** [comment]
Hi, just to let you know that I'm still having this issue after updating to v3.4.4

**Comment by inspireui** [comment]
Hi @MechEight could you send us (support@inspireui.com) your website URL and the consume key connect to your site - we will have a check on your site - thank you!

**Comment by MechEight** [comment]
@inspireui The issue happened only on my local woocommerce installation. After setting up our online server and connecting to that, logging in works fine so I'll close the issue. Thanks.

**Comment by inspireui** [comment]
Thank you for your update

**Comment by hefejeff** [comment]
I am getting this same issue on a brand new install with wp and woo hosted on online.  Any help would be greatly appriciated.  The bug appears to be in the request function in the omni file.
