### ISSUE TITLE
Unable to resolve ./layouts

### ISSUE THREAD

**Issue by louierosero-gss** [inspireui/mstore#110]
Unable to resolve ./layouts" from "./C:\\Users\NAME\\Desktop\\BeoNews\\beonews-expo\\App\\Redux\\reducers\\index.js": could not resolve "./C:\\Users\NAME\\Desktop\\BeoNews\\beonews-expo\\App\\Redux\\reducers\\layouts' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]},"type":"bundling_error"}"

I got this error after downloading the latest version 2.8.0 of BeoNews.

Below is the following procedure that I make.
> After downloading the latest version. I open the config.js from the App/Common folder and change the URL root to my wordpress link.
> Next is install the yarn in the beonews-expo folder.
> Open the beonews-expo in XDE Expo and run it in the Genymotion Emulator (Android Nexus 5).

**Comment by louierosero-gss** [comment]
This issue is resulted by merging the previous version and the latest version 2.8.0 of BeoNews.

**Comment by inspireui** [comment]
Thank you for your noted @louierosero-gss
