### ISSUE TITLE
blank page after adding new payment gateway 

### ISSUE THREAD

**Issue by mezzat11** [inspireui/mstore#111]
i get black page in the app after adding new payment gateway
![screenshot_1514390406](https://user-images.githubusercontent.com/34794248/34410503-89c2267a-ebd9-11e7-82ba-bc40bc8c9f48.png)
working on website normally ! 

more details sent by email

**Comment by mezzat11** [comment]
same problem after updating to 3.4.4

**Comment by inspireui** [comment]
Hi, could you open Reactotron which can be install by this guide https://mstore.gitbooks.io/mstore-manual/content/chapter2.html - then send us the URL when you request the mstore-checkout URL to the server ?

**Comment by mezzat11** [comment]
https://goo.gl/jysVq8

**Comment by mezzat11** [comment]
same blank page 
working normally from web !

**Comment by mezzat11** [comment]
????

**Comment by inspireui** [comment]
Hi, did you try to update the latest plugin https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout ?

Can you comment the line 491 from the file /plugins/mstore-checkout/templates/mstore-checkout-template.php on your side then resend me the link, your submit form when payment could have an issue

**Comment by inspireui** [comment]
Hi @mezzat11 it looks ok with the payment but we could find out was blank after submit (http://khtwah.info/store/checkout/) could you try to config subdomain - store.khtwah.info, instead of /store ?

**Comment by inspireui** [comment]
Linked to https://github.com/inspireui/mstore/issues/114 could be the same root cause - we will investigate

**Comment by mezzat11** [comment]
but #114 problem happen with arabic strings
this problem happen with english ( like link i sent to you ) !
