### ISSUE TITLE
Build Failed 3.4.3

### ISSUE THREAD

**Issue by Snakepli** [inspireui/mstore#113]
Build Failed with Store : 

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze RCTLocationObserver.m
(1 command with analyzer issues)

The following build commands failed:
	CompileC /Users/adrien/Downloads/mstore-v3.4.3/mstore-pro/ios/build/Build/Intermediates.noindex/RCTGeolocation.build/Debug-iphonesimulator/RCTGeolocation.build/Objects-normal/x86_64/RCTLocationObserver.o RCTLocationObserver.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I add React in scheme and uncheck Parellelize Build
I have FacebookSDK in documents
I tried watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache clean && npm install && react-native link && npm start -- --reset-cache
I clean the cache of Xcode project

Do you have an idea for fix it ?

Purchase code : 6fb67ff9-7366-4d73-a6db-6ab576b63f7d

**Comment by inspireui** [comment]
Could you try to run it from Xcode ?

or try to run the script to see what's happen:
`node node_modules/react-native/local-cli/cli.js bundle --entry-file='index.ios.js' --bundle-output='./ios/beostore/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios`

**Comment by Snakepli** [comment]
Thanks. Works.
