### ISSUE TITLE
issue when order  product with utf-8 title

### ISSUE THREAD

**Issue by mezzat11** [inspireui/mstore#114]
![screenshot_1514390094](https://user-images.githubusercontent.com/34794248/34444626-182ff384-ecd8-11e7-9c73-0e963733c484.png)

**Comment by inspireui** [comment]
Could you pasted the title string that cause the issue? it looks ok with my testing for the utf8 title

**Comment by mezzat11** [comment]
I discovered that the problem was due to address fields " when enter UTF-8 like arabic strings 
عنوان تجريبي 
' the problem happened

**Comment by mezzat11** [comment]
working normally when selection payment method " cash on delivery " 
but get this error when select any other payment methods which using webview

**Comment by inspireui** [comment]
Hi, could you you send us the mstore-checkout URL from Reactotron (https://mstore.gitbooks.io/mstore-manual/content/chapter2.html) when process the payment, we will help to investigating. Btw, we are checking the arabic string - thank you!

**Comment by mezzat11** [comment]
![2018-01-11_111835](https://user-images.githubusercontent.com/34794248/34817663-35298ed0-f6c1-11e7-9be7-6c66aab26f87.jpg)
logs not reach to mstore-checkout url 
{
  "message": "InvalidCharacterError: The string to be encoded contains characters outside of the Latin1 range.\n\nThis error is located at:\n    in Cart (created by Connect(Cart))\n    in Connect(Cart) (at CartScreen.js:18)\n    in CartScreen (at SceneView.js:31)\n    in SceneView (at CardStack.js:394)\n    in RCTView (at View.js:112)\n    in View (at CardStack.js:393)\n    in RCTView (at View.js:112)\n    in View (at CardStack.js:392)\n    in RCTView (at View.js:112)\n    in View (at createAnimatedComponent.js:134)\n    in AnimatedComponent (at Card.js:26)\n    in Card (at PointerEventsContainer.js:55)\n    in Container (at CardStack.js:436)\n    in RCTView (at View.js:112)\n    in View (at CardStack.js:365)\n    in RCTView (at View.js:112)\n    in View (at CardStack.js:364)\n    in CardStack (at CardStackTransitioner.js:97)\n    in RCTView (at View.js:112)\n    in View (at Transitioner.js:187)\n    in Transitioner (at CardStackTransitioner.js:49)\n    in CardStackTransitioner (at StackNavigator.js:60)\n    in Unknown (at createNavigator.js:52)\n    in Navigator (at createNavigationContainer.js:216)\n    in NavigationContainer (at index.js:88)\n    in screen (at SceneView.js:31)\n    in SceneView (at TabView.js:82)\n    in RCTView (at View.js:112)\n    in View (at TabView.js:81)\n    in RCTView (at View.js:112)\n    in View (at TabViewPagerPan.js:294)\n    in RCTView (at View.js:112)\n    in View (at createAnimatedComponent.js:134)\n    in AnimatedComponent (at TabViewPagerPan.js:284)\n    in TabViewPagerPan (at TabView.js:165)\n    in RCTView (at View.js:112)\n    in View (at TabViewAnimated.js:252)\n    in TabViewAnimated (at TabView.js:225)\n    in TabView (at withCachedChildNavigation.js:66)\n    in withCachedChildNavigation(TabView) (at TabNavigator.js:65)\n    in Unknown (at createNavigator.js:52)\n    in Navigator (at createNavigationContainer.js:216)\n    in NavigationContainer (at Router.js:69)\n    in RCTView (at View.js:112)\n    in View (at Router.js:67)\n    in RCTView (at View.js:112)\n    in View (at DrawerLayoutAndroid.android.js:186)\n    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)\n    in DrawerLayoutAndroid (at MenuScale.js:39)\n    in MenuScale (at Router.js:66)\n    in Provider (at Router.js:65)\n    in Router (at ReduxWrapper.js:124)\n    in Provider (at ReduxWrapper.js:123)\n    in ReduxWrapper (at renderApplication.js:35)\n    in RCTView (at View.js:112)\n    in View (at AppContainer.js:102)\n    in RCTView (at View.js:112)\n    in View (at AppContainer.js:122)\n    in AppContainer (at renderApplication.js:34)",
  "stack": [
    {
      "functionName": null,
      "lineNumber": 23,
      "columnNumber": 35,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\base-64\\base64.js"
    },
    {
      "functionName": null,
      "lineNumber": 165,
      "columnNumber": 2,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\base-64\\base64.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 23,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\react-native-fetch-blob\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 3,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\react-native-img-cache\\build\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 3,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\components\\ImageCache\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 34,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\components\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 10,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\containers\\Categories\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 4,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\containers\\index.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 8,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\Router.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 19,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\src\\ReduxWrapper.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 138,
      "columnNumber": 36,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": null,
      "lineNumber": 4,
      "columnNumber": 0,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\index.android.js"
    },
    {
      "functionName": "loadModuleImplementation",
      "lineNumber": 191,
      "columnNumber": 12,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "guardedLoadModule",
      "lineNumber": 131,
      "columnNumber": 45,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "_require",
      "lineNumber": 118,
      "columnNumber": 20,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\metro-bundler\\src\\Resolver\\polyfills\\require.js"
    },
    {
      "functionName": "global code",
      "lineNumber": 177,
      "columnNumber": 5,
      "fileName": "E:\\mstore-v3.4.44\\mstore-pro\\node_modules\\tween-functions\\index.js"
    }
  ]
}

**Comment by techview51** [comment]
I have  the same problem: [InvalidCharacterError: The string to be encoded contains characters outside of the Latin1 range #143](https://github.com/inspireui/mstore/issues/143)
Maybe the reason is realted to encryption and decryption fucntions.... Hope to find a solution ASAP.
