### ISSUE TITLE
Bug: Search Products Not Working

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#115]
Hey there,

I finished integrating a lot of features on Mstore through my website: https://smartify.in. 

I'm only left with one critical one, which is-- Search.

Here's what happens when I try to search by product name: 

![screen shot 2017-12-30 at 10 26 56 am](https://user-images.githubusercontent.com/12051018/34451449-013da8a0-ed4c-11e7-9954-2dbe9a00df6c.png)

![screen shot 2017-12-30 at 10 27 41 am](https://user-images.githubusercontent.com/12051018/34451453-180d3122-ed4c-11e7-9d40-2eea24927b3c.png)

Any help on how to enable WooCommerce search would be highly appreciated.

Store address: https://smartify.in/store

Thanks,
Shweta

**Comment by inspireui** [comment]
Could you try to open Reactotron - https://mstore.gitbooks.io/mstore-manual/content/chapter2.html and send us the URL when processing search on your website ?

**Comment by shweta-bavishi** [comment]
Here’s the screenshot from React-Tron: 



And here’s the website URL: https://smartify.in/shop/ <https://smartify.in/shop/>

**Comment by shweta-bavishi** [comment]
There’s an another issue https://github.com/inspireui/mstore/issues/121 <https://github.com/inspireui/mstore/issues/121>. Can you please solve this issue too?

**Comment by inspireui** [comment]
@shweta-bavishi  i could not see the "screenshot from React-Tron" pls upload it again.

**Comment by shweta-bavishi** [comment]
![screen shot 2018-01-09 at 10 32 08 am](https://user-images.githubusercontent.com/12051018/34705714-7817c8a0-f528-11e7-8389-e45aee9e7621.png)

**Comment by abhibavishi** [comment]
Hi @inspireui, can you please resolve the above error, asap? We are almost ready for launch, but search is not working on the app, right from the start. It's working fine on the website, and also on the Wordpress portal.

**Comment by inspireui** [comment]
could you send the config.js file on that site to my email: support@inspireui.com, then i can debug from our side - thank you!

**Comment by abhibavishi** [comment]
The config file has been sent a couple of days back. Can you please check, again? We are only awaiting your help on this issue.

**Comment by inspireui** [comment]
you can submit refund for this product if you are happy with the product, thanks

**Comment by abhibavishi** [comment]
It's not working for me. If it's not a bug, it should work, right? How much would you guys charge for making search work, from the server side? 

I don't want any refund; I want to launch the app, as soon as possible.
