### ISSUE TITLE
Error signup with update "Hello Undefined"

### ISSUE THREAD

**Issue by martinledjo** [inspireui/mstore#116]
When i signup on the app i have the message "Hello undefined" and i'm am not connected
![image](https://user-images.githubusercontent.com/34414960/34463418-a3c7d75c-ee5b-11e7-8ac5-8538a272daf2.png)

**Comment by martinledjo** [comment]
and the issues news are not fix on expo version !

**Comment by martinledjo** [comment]
On expo version, i can see pictures, 0 pictures for products 0 pictures for categories, 0 pictures for news
![image](https://user-images.githubusercontent.com/34414960/34470971-1a10863e-ef3d-11e7-94a3-9a91bc4e90fb.png)

**Comment by martinledjo** [comment]
and the news issues are not fixed in expo version

**Comment by martinledjo** [comment]
I have resolve the signup

**Comment by inspireui** [comment]
Thank you for your quickly updated. You can copy the sign in component from pro to expo version as well.
