### ISSUE TITLE
Unable to reach bottom of product page

### ISSUE THREAD

**Issue by eric90066** [inspireui/mstore#117]
The responsiveness and performance of the product pages and categories pages are much improved with v3.4.4.  It finally brings hope that the app is finally working with my website. 

The issue now is - when scrolling down the page there is clearly additional information/text that I cannot reach because the scroll will not go down far enough. 

Please advise. 

In addition - can you please tell me how to change the main image on the home page?

![screen shot 2018-01-01 at 5 00 41 pm](https://user-images.githubusercontent.com/5639308/34471363-6a625478-ef15-11e7-9fa4-1d9316056a2a.png)

**Comment by inspireui** [comment]
Hi, there is the HorizonLayout section from the config.js file where you can config for the layout banner

**Comment by eric90066** [comment]
Perhaps I am looking at the wrong place.  The image above "Brand New" is appearing the the category Brand New.  That image's name is Feature.  What is the name of the image on the home page. 


In addition, added some new items on the site and for some of them I am getting the following error


![screen shot 2018-01-05 at 11 03 50 am](https://user-images.githubusercontent.com/5639308/34617355-27e108d2-f209-11e7-8056-f5c0655ac562.png)

and 


![screen shot 2018-01-05 at 11 05 46 am](https://user-images.githubusercontent.com/5639308/34617366-340b354c-f209-11e7-84fa-cfa54ea1ab4d.png)

and

![screen shot 2018-01-05 at 11 20 24 am](https://user-images.githubusercontent.com/5639308/34617790-88863bfc-f20a-11e7-91ca-253f220e63d9.png)

This is very concerning.  Will the app throw error on all new items added to the site?

**Comment by eric90066** [comment]
Are we getting any updates here????  I posted my issues almost two weeks ago.

**Comment by inspireui** [comment]
[index.js.zip](https://github.com/inspireui/mstore/files/1637511/index.js.zip)

As far as our team investigate with this issue it was caused by the webview when showing some detail post, please try to copy the attache file and override to Components/WebView/index.js 

Make sure to run 'yarn install sanitize-html' to use this component 

Let us know your checking from your side.

**Comment by inspireui** [comment]
closed, let me know if you still trouble with this solution - thank you!
