### ISSUE TITLE
Images are not coming in physical device.

### ISSUE THREAD

**Issue by brst-pc70** [inspireui/mstore#118]
We setup the mstore code on our server and generate the consumerKey and consumerSecret. These keys we are using in the react native app, data and images are coming in simulator, but when we use the physical device, only data is showing not the images. When we use the given  consumerKey and consumerSecret of mstore app, images and data are shown in both physical and virtual device. Please help in this issue.

**Comment by inspireui** [comment]
Hi, are you using from local server or hosting, please share your URL then we could have a check? If you are using from local then make sure your device can reach to the local url (virtual host). Thank you!

**Comment by brst-pc70** [comment]
Here is the url and keys which i am using for getting data :
url: "http://beta.brstdev.com/eshop"
consumerKey: "ck_90ae67caa12282124c4b3987ba0cee86c9ee6dbe",
consumerSecret: "cs_8b388684cc26dc0e5c389efeb42ad8e62178dd82"

**Comment by inspireui** [comment]
[Tools.js.zip](https://github.com/inspireui/mstore/files/1613714/Tools.js.zip)

Hi, could you try to extract then override this file to src/common/Tools.js to see if it can be fixed your issues.

If it could not fixed, try to send us some category id for tag if from your backend side to config the HorizonLayout, is it all ok from your local side?
