### ISSUE TITLE
Error - product.attributes.length

### ISSUE THREAD

**Issue by ArabAgile** [inspireui/mstore#12]
Hi,

When first running on Expo, I got this error:

`undefined is not an object (evaluating 'product.attributes.length')`

The response from API is empty array `[]`

This is my first run for the app.

Any idea?

**Comment by thangvo9x** [comment]
Hi @ArabAgile, you can talk to me , which is your product type, plz ? ( simple, variable...)

**Comment by thangvo9x** [comment]
Okie. This problem was fixed in mstore version  3.2. We'll upgrade soon !

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 are fixed this issue. Please help to open new ticket if there are still issue. Thank you so much for your feedback
