### ISSUE TITLE
Focus on TextInput in the ScrollView have bug

### ISSUE THREAD

**Issue by mgolkardev** [inspireui/mstore#120]
Hi
When typing, if you tap on another TextInput, the keyboard closes.

![0000111](https://user-images.githubusercontent.com/4500080/34534595-f2f0a80c-f0d3-11e7-94f9-63c8970b130c.gif)

https://github.com/facebook/react-native/issues/17434
 
Thanks.

**Comment by inspireui** [comment]
Thank you, could be the Android OS issue, could you try on difference android version ?

**Comment by mgolkardev** [comment]
Hi
The bug fixed.
please see facebook/react-native#17434
Thanks.
