### ISSUE TITLE
Table elements are not showing in the description section

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#121]
On passing the following div element to the description section:

```
<div class="productDescriptionWrapper">
<a href="https://smartify.in/knowledgebase/setup-osram-lightify/" target="_blank" rel="noopener noreferrer">Get Started</a> with the Home Automation lighting experience with your OSRAM LIGHTIFY starter Kit which comes with a LIGHTIFY Gateway and LED RGBW light bulb. Explore the fun of colors and mood lighting from 16 million color options as well as the comfort of cool and warm shades.
<table style="width: 100%; margin-left: auto; margin-right: auto; margin-top: 2em;" border="0">
<tbody>
<tr>
<td>
<p style="text-align: center;"><img class="alignnone size-full wp-image-3500" src="https://smartify.in/wp-content/uploads/2016/08/OSRAM-LIGHTIFY-key-features-01.jpg" alt="OSRAM LIGHTIFY key features 01" width="300" height="299" /></p>
</td>
<td style="width: 50%; padding-left: 15px; padding-top: 35px;">
<h3><strong>Infinite World of Colors</strong></h3>
Use the power of colors and live every moment of your life to its peak. Just swipe through the color wheel in the LIGHTIFY App and fill your rooms with the best option available that suits your mood.
You can select between 16 million color options to several white shades.</td>
</tr>
</tbody>
</table>
</div>

```
The Description section in the woocommerce website is:
![tableerror](https://user-images.githubusercontent.com/12051018/34560133-b401927c-f16a-11e7-864b-f678f092ca6e.png)

Whereas, in the simulator the table element is not visible and moreover the link in the description section cannot be opened:
![tableerror2](https://user-images.githubusercontent.com/12051018/34560314-4bc62c1c-f16b-11e7-886e-b09f5798949e.png)

**Comment by inspireui** [comment]
Hi we are checking this issue and will have patching if we can find a bug on next v3.4.5 - thank you!

**Comment by shweta-bavishi** [comment]
I've solved the issue by making some of the changes in the code. Tables can be rendered inside the component by removing "table","tr" and "td" from the IGNORED_TAGS in the react-native-render-html library. Moreover, link can be opened by adding the method "Linking.openURL()"
