### ISSUE TITLE
The android release app crash at start

### ISSUE THREAD

**Issue by martinledjo** [inspireui/mstore#124]
I did all the tasks of the documents : https://mstore.gitbooks.io/mstore-manual/content/ all work great for ios i don't have problem but on android the app crash at start when i make a release app. I don't understand because the react-native run-android work great. I don't have warnings or errors when i build.

**Comment by inspireui** [comment]
Hi it could be caused by missing config from your release mode on Android, can you try to install https://github.com/getsentry/react-native-sentry then investigate the crashing issue. Also have a look to this detail user guide -https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by martinledjo** [comment]
it's fix but i have a question, why on android 
![image](https://user-images.githubusercontent.com/34414960/34718140-dbb4ea2a-f535-11e7-8b8b-4bba86c8382b.png)
the "URL" custom page make a blank screen and don't show the content.
I want to show a user panel but it's impossible with "ID wordpress" custom page with iframe and redirection because the width and scale is bad.

**Comment by inspireui** [comment]
we are checking the issue and it will fix on next version - thank you!

**Comment by martinledjo** [comment]
I want to upload my app for the 20 january, the update will be release before the 20 ?

**Comment by martinledjo** [comment]
please fix this too
![image](https://user-images.githubusercontent.com/34414960/34817987-c4d3e524-f6b9-11e7-8fb5-a0c372f7194d.png)

**Comment by martinledjo** [comment]
I fixed CUSTOMPAGESCREEN by changing "url" to "URI".
But there is a problem, the input file does not work because the WEBVIEW of react-native for android is not compatible with the input file.

Can you help me ?

**Comment by inspireui** [comment]
Hi @martinledjo please try to update the styles.js from the PostLayout to fixed the issue with your currency, this could be quick job by adjust the height and padding.

Could you show us your URL then we can test and fix on the Android
