### ISSUE TITLE
The variants are not scrollable

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#126]
When I try to open the product, the variants of the products are not scrollable, when there are more than 4 options. 
![variant](https://user-images.githubusercontent.com/12051018/34840548-5155f750-f72b-11e7-9e90-26e75108063e.png)
Kindly suggest how to make it scrollable.

**Comment by calebdomingo** [comment]
same problem here

**Comment by inspireui** [comment]
could you try with this fix, replace View by Scrollview (file Containers/Detail/index.js)

<img width="1109" alt="screen shot 2018-01-16 at 10 58 21 pm" src="https://user-images.githubusercontent.com/29778334/34998128-d4f21a4c-fb10-11e7-90ea-71db4f97dd17.png">

**Comment by shweta-bavishi** [comment]
I have tried this fix. The code that I changed is:

```
    const renderAttributes = () => <View>
      {typeof this.productAttributes !== "undefined" && this.productAttributes.map((attribute, attrIndex) => (
        <ScrollView key={"attr" + attrIndex}
              style={[styles.productSizeContainer, Constants.RTL && {flexDirection: 'row-reverse'}]}>
          {attribute.name !== Constants.productAttributeColor && attribute.options.map((option, index) =>
            <ProductAttribute key={index}
                              text={option}
                              style={styles.productSize}
                              onPress={() => this.onSelectAttribute(attribute.name, option)}
                              selected={attribute.selectedOption.toLowerCase() === option.toLowerCase()}/>
          )}
        </ScrollView>))}
    </View>
```

On making the following changes, when I click on the product, it shows me the following error:
![simulator_ss](https://user-images.githubusercontent.com/12051018/35052790-711ae148-fbce-11e7-923a-297f08b2b1c3.png)

**Comment by inspireui** [comment]
Hey sorry, i was mean this 

`const renderAttributes = () => < ScrollView >
      {typeof this.productAttributes !== "undefined" && this.productAttributes.map((attribute, attrIndex) => (
        <View key={"attr" + attrIndex}
              style={[styles.productSizeContainer, Constants.RTL && {flexDirection: 'row-reverse'}]}>
          {attribute.name !== Constants.productAttributeColor && attribute.options.map((option, index) =>
            <ProductAttribute key={index}
                              text={option}
                              style={styles.productSize}
                              onPress={() => this.onSelectAttribute(attribute.name, option)}
                              selected={attribute.selectedOption.toLowerCase() === option.toLowerCase()}/>
          )}
        </View>))}
    </ScrollView >
`

**Comment by shweta-bavishi** [comment]
Thank you. This solution worked for me 👍

**Comment by Brdnn** [comment]
Hi, I am facing the same issue and I fixed them with the solution above. However, its just fixed iOS version but Android version is still not scrollable. Any solution for this?
