### ISSUE TITLE
Reviews cannot be posted

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#127]
Under the product section, the reviews can be viewed but there is not an option to post a review. So can you help me with implementing this functionality
![whatsapp image 2018-01-12 at 1 49 41 pm](https://user-images.githubusercontent.com/12051018/34865870-5f2a23b8-f7a0-11e7-92c3-2575c4528c0d.jpeg)

**Comment by inspireui** [comment]
Hi, we have update this as the request feature and will consider to update on later versions - thank you for your suggestion

**Comment by poekong** [comment]
Great! I am waiting for this as well.

**Comment by inspireui** [comment]
Noted, move to ticket support please move to https://inspireui.ticksy.com/ - Thank you !
