### ISSUE TITLE
MStore Pro: Shows Nothing, No Products, No Categories, No Images

### ISSUE THREAD

**Issue by techview51** [inspireui/mstore#128]
I bought Pro version. Carefully done everything described in docs.
No result. Just works on your site. I checked 2 websites and no success.
I started with the Android version.
Help plz.

**Comment by Ghulamhaider12** [comment]
same problem here

**Comment by naserbeheshti** [comment]
@inspireui , I checked with predefined and 2 other sites, the problem still exists.
The problem also exists in beonews.

There is a serious problem:
1. Your setup guide asks to install JSON API plugin, which has a default path to retrieve data from "api" path:
mydomain.com/**api**
but your app code calls JSON data from another path. For example:
**/wp-json/wp/v2/**
You can see this conflict in "WordpressApi.js" file for example.

I tried to change the path, I have two types of error:
First, if the path doesn't exist, Forbidden 403 raises.
Second, if the path exists, rest_no_route 404 raises.

And, I am confused the way you are using the REST functions. The functions you are using to post and get data in "JSON" are valid for WP REST API V2 which is included from Wordpress 4.7. But your documents asks us to install JSON API plugin that uses different function syntax.

**Comment by inspireui** [comment]
Hi @naserbeheshti most of the feature API is still use the default Wordpress 4.7, the JSON API  is only use the registration user feature as the default api is not supported. 

You can share your config.js file here then we will help to check your issue - thank you!

**Comment by techview51** [comment]
@inspreui, Thanks. I know about config. There were other problems. I handled them.
