### ISSUE TITLE
Invalid version: "3.1"

### ISSUE THREAD

**Issue by LuisJorgeAr** [inspireui/mstore#13]
Hello, I hadn't been able to run the app, tried expo but I am getting an error message, please take a look at the attached picture and provide your input.

<img width="1178" alt="invalid version 3 1" src="https://user-images.githubusercontent.com/29908602/28193512-fb720bce-6802-11e7-8d5e-0271ecfe0a0c.png">

Note: I followed the React Native installation steps and was able to create a new project and run an iOS project successfully from the command line and using expo, too. So, it seems this relates to the provided package or to the lack of clear instructions on troubleshooting.

Thanks

**Comment by inspireui** [comment]
Hi after install the library by: yarn install (or npm install) you may need to restart the expo again

**Comment by thangvo9x** [comment]
Hi @LuisJorgeAr , you should restart expo again by press Shift button and click Restart. They was be cleared

**Comment by hazephase** [comment]
I am getting the same errors and I am unable to install yarn also. I get this error when I install yarn

**Comment by inspireui** [comment]
I could you try with new v3.2 update and let me know it still an issue. Thank you!
