### ISSUE TITLE
mstore Registation error

### ISSUE THREAD

**Issue by Ghulamhaider12** [inspireui/mstore#130]
![Uploading Screenshot_20180116-151341 (1).png…]()
]

**Comment by Ghulamhaider12** [comment]
![screenshot_20180116-151341 1](https://user-images.githubusercontent.com/27043983/34989441-59b552c6-fae4-11e7-927b-1624ef590256.png)

**Comment by Ghulamhaider12** [comment]
please help me

**Comment by inspireui** [comment]
Please update the latest v3.4.4 and also the plugins from https://github.com/inspireui/mstore/tree/master/plugins will fix this issues
