### ISSUE TITLE
Variants not displaying correct price

### ISSUE THREAD

**Issue by calebdomingo** [inspireui/mstore#131]
Hello,

There seems to be a bug with the variants. When selecting variants with different prices, the correct product pricing does not update. Using expo version for this.

Thanks!

**Comment by inspireui** [comment]
Hi, we will have a check on this issue

**Comment by Brdnn** [comment]
Hi, variant product does change the price of the product but it doesnt change the product image respectively. looking forward for new update! Cheers

**Comment by inspireui** [comment]
@Brdnn fixed
