### ISSUE TITLE
‘React/RCTBridgeModule.h’ file not found

### ISSUE THREAD

**Issue by xa9** [inspireui/mstore#132]
‘React/RCTBridgeModule.h’ file not found

I have a problem and I am tired to solve it and have used more than one solution and no modification of the problem.

solution 1 :

I check the solution here – https://mstore.gitbooks.io/mstore-manual/content/chapter7.html and no modification .

solution 2 : I try with this script to see if it can be fixed – https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9 and no modification .

can you solve it ???

thanks ,

**Comment by inspireui** [comment]
Hi could you share your screenshot from Edit schema base on this guide - https://mstore.gitbooks.io/mstore-manual/content/chapter7.html 

And show us the detail log and click to red icon warning on XCode

**Comment by xa9** [comment]
ok 
![screen shot 2018-01-19 at 10 05 47 pm](https://user-images.githubusercontent.com/29809274/35167208-adc3f790-fd65-11e7-8b82-dfd3b43a4e3b.png)
![screen shot 2018-01-19 at 10 06 38 pm](https://user-images.githubusercontent.com/29809274/35167209-adff3a08-fd65-11e7-9886-b16728d408fa.png)
![screen shot 2018-01-19 at 10 09 50 pm](https://user-images.githubusercontent.com/29809274/35167235-beb957b6-fd65-11e7-8e70-9f3c945728a2.png)
![screen shot 2018-01-19 at 10 10 02 pm](https://user-images.githubusercontent.com/29809274/35167237-bfc02c16-fd65-11e7-981e-9dd28603f229.png)
![screen shot 2018-01-19 at 10 10 37 pm](https://user-images.githubusercontent.com/29809274/35167244-ca4944d8-fd65-11e7-9db9-91596b5c4922.png)
![screen shot 2018-01-19 at 10 10 27 pm](https://user-images.githubusercontent.com/29809274/35167252-d16879a0-fd65-11e7-8ba6-c935c7e61464.png)

**Comment by inspireui** [comment]
<img width="1002" alt="screen shot 2017-12-13 at 9 10 05 pm" src="https://user-images.githubusercontent.com/29778334/35178920-9ce10122-fdc2-11e7-8676-9616c12b9a18.png">

Hi, it is not the same as screenshot, please try to uncheck the parallize Build and the React should be ordered on top

**Comment by xa9** [comment]
thanks , its ok sorry 👍

**Comment by inspireui** [comment]
no worries, kindly close the issue if you have resolved it :)

**Comment by xa9** [comment]
ok , you can close it 


thanks a lot
