### ISSUE TITLE
RCTOneSignal.h Not found

### ISSUE THREAD

**Issue by leutrimraifi** [inspireui/mstore#134]
I want to build for ios but i have this problem OneSignal.h not found plus for facebook sdk i see on my Documts i dont have folder with name FacebookSDK i create it and i past it from your link it is ok ?

**Comment by inspireui** [comment]
@leutrimraifi yes it is ok, you can create the folder and paste all file to there, like this screenshot

Then try to run "react-native link" from your project folder and execute the app again. 
Thank you!

<img width="717" alt="screen shot 2018-01-24 at 3 36 11 pm" src="https://user-images.githubusercontent.com/29778334/35322312-61efb6dc-011c-11e8-9729-fa73f3e5e4bf.png">

**Comment by inspireui** [comment]
<img width="1619" alt="screen shot 2018-01-24 at 4 43 08 pm" src="https://user-images.githubusercontent.com/29778334/35325270-ca145570-0125-11e8-9449-e57656e714d5.png">

You can also try to remove reference the RCTOneSignal.xcodeproj and drag it again from the node_module/react-native-onesignal/ios folder
