### ISSUE TITLE
Some smalls problems

### ISSUE THREAD

**Issue by dweb2012** [inspireui/mstore#135]
Hello
1) I have Only One category, how to display in the homepage posts as card without slider (as in the category page) ?
2) How to restrict news to a specific category ?
3) Contact page having form contact in the original website, how can i make it working or adding basic contact form ?
4) Added new menu item 
`WebPages:` {marketing: `'https://www.yahoo.com/'},`  
Menu item diplayed but nothing happens when I click on it !
5) How to change App name "MStore" in Android device ?

Thank you in advance

**Comment by inspireui** [comment]
Hi

1. You can edit the HorizonLayout from config.js file to update the layout and category

2. This feature is not support from the config but you could edit the function fetchNews from redux/NewsRedux.js 

3. You can use WebView to load whole page then the js will be support - https://facebook.github.io/react-native/docs/webview.html

4. Let try with other URL as the Webview could limit to some webpage.

5. This could be changed from android/src/main/res/values/strings.xml

Thanks
