### ISSUE TITLE
Add a welcome or intro text

### ISSUE THREAD

**Issue by dweb2012** [inspireui/mstore#136]
Hello
How to add a welcome text in the homepage ?
Thank you

**Comment by inspireui** [comment]
<img width="1215" alt="screen shot 2018-01-25 at 8 48 54 am" src="https://user-images.githubusercontent.com/29778334/35366538-99bf105e-01ac-11e8-9429-0b26159aa0c6.png">

We have the welcome message after user login success full, you can use similar method with toast function, or if you would like to show as the banner hompage, edit it from HorizonLayout - config.js file

Hope this help. Thank you!
