### ISSUE TITLE
Custom pages not working for android

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#137]
I want to customize my Custom page. So I've added following code in Constants.js file:

`WebPages: {Marketing: 'https://smartify.in/contact-us/'}`

The custom pages are loading perfectly fine for iOS devices, but showing blank pages for android devices

**Comment by levi-beers** [comment]
I too am experiencing this. The custom webview pages work on iOS but just show a white page with the tabbar visible on Android. Any quick fix that we can do on our end for this issue?

**Comment by levi-beers** [comment]
To resolve the issue of Custom WebView pages not working on Android devices, locate the src/navigation/CustomPageScreen.js file and change the WebView controller to "uri" not "urL"

`return <WebView source={{uri: state.params.url}}/>`

**Comment by shweta-bavishi** [comment]
The solution worked for me.. Thanks :) 
But I am not able to see any menu option at the top of the controller. So is there any solution for that?

**Comment by levi-beers** [comment]
I'm working on that issue in my app today. If I'm able to overcome the problem I'll post my workaround.

**Comment by inspireui** [comment]
Thank you so much for your help @levi-beers 

Confirm change url to uri will fix the issue (it will be update on next version) as well
