### ISSUE TITLE
Cannot find entry file index.android.js in any of the roots:

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#138]
I unzipped mstore-pro.zip file, did 'yarn install' in cmd, and it succeeded.
When I run android studio with 'react-native start', this error shows.
What is the reason?

<img src='https://image.prntscr.com/image/fsdr5bhzQ_WdazndSEx32Q.png'>
</iimg>

**Comment by levi-beers** [comment]
If you are receiving this error using an actual Android device try using the Android simulator to see if it goes away. See https://github.com/facebook/react-native/issues/15070 for more information. To test on a physical device, I had to build the APK and install that way.

**Comment by lin-zy1229** [comment]
I resolved this issue, changing project's `build.gradle`
from
`url "$rootDir/../node_modules/react-native/android"`
to
`url "$rootDir/node_modules/react-native/android"`
