### ISSUE TITLE
Two error in app splash page 

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/mstore#139]
1)Splash page not load in app how can i config it
2)minni bannar not load i dont know why
Can i make minibannar photo 
![screenshot_20180130-110341](https://user-images.githubusercontent.com/35544603/35619453-c8632c36-0686-11e8-8d60-10ec7d90e22b.png)

**Comment by inspireui** [comment]
1. splash screen on Android have a bug and we will resolve on v.3.4.5 - https://github.com/inspireui/mstore/issues/104
2 you can double check the config for your miniBanner, make sure the tag id or category is correctly

**Comment by mohamedibrahim89** [comment]
Can i make banner photo not product
If i can how plz
