### ISSUE TITLE
Unable to install Yarn

### ISSUE THREAD

**Issue by hazephase** [inspireui/mstore#14]
I am unable to install Yarn on mac I am getting a error. 

Error: No available formula for yarn 
Searching formulae...
Searching taps...

**Comment by alien3d** [comment]
cd /usr/local/Library/Formula
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/yarn.rb
brew install yarn

**Comment by hazephase** [comment]
so I should add the yarn.rb file to the folder cd /usr/local/Library/Formula?

**Comment by hazephase** [comment]
I am getting a -bash: Wget: command not found
error

**Comment by hazephase** [comment]
I got it fixed by using curl -O in plaec on Wget
