### ISSUE TITLE
Solution: payment section problem

### ISSUE THREAD

**Issue by emiryayla** [inspireui/mstore#140]
where i can resize in app images which css file 
and why when i trying in payment section (webview) show 404 page not found?

![simulator screen shot - iphone 8 plus - 2018-01-30 at 16 57 20](https://user-images.githubusercontent.com/17924493/35570719-0a1904f8-05e1-11e8-95f9-3edf2be26cf4.png)

**Comment by smdanishiqbal** [comment]
same issue .
![27745070_1813673225330248_1871169900_o](https://user-images.githubusercontent.com/10116452/35766612-6d688c26-08fd-11e8-8521-e5d1cc760af9.png)

**Comment by inspireui** [comment]
At @emiryayla and @smdanishiqbal please share your config.js file to our support email support@inspireui.com we will help to have a check on your site - thank you!

**Comment by calebdomingo** [comment]
I have the same problem but with PayPal. It shows a 404 error when checkout button is pressed. I hope you guys can fix this asap.

**Comment by smdanishiqbal** [comment]
@inspireui  any update regarding my issue ?? i already sent mail to support team but haven't receive any response yet.

**Comment by Brdnn** [comment]
I am also facing the same issue which showing error 404 page after checkout with paypal. Any solution so far?

**Comment by Brdnn** [comment]
Thanks @stmkpj for the solution for this issue. 
You have to create a new page name it: "mstore-checkout". Then select "Custom Page Template" as your page template for it.

![image](https://user-images.githubusercontent.com/36357486/36201352-adfcd3ee-11ba-11e8-9262-9e09a320a19e.png)

**Comment by smdanishiqbal** [comment]
@Brdnn  Will u please explain it in steps? 
I already created a msotre-checkout page in wordpress site but now its showing empty page ??

**Comment by Brdnn** [comment]
@smdanishiqbal Firstly you need to create a page and name it "mstore-checkout" and remember dont set any parent page for it, then set page template to"page custom template". 
*You need to install the mstore-checkout plugin at the first place.

Below is the screenshot for how to setting:
![image](https://user-images.githubusercontent.com/36357486/36218009-fcd213de-11ed-11e8-82ca-bae4bead8dc3.png)

**Comment by andybedoy** [comment]
Do the steps and tell me invalidate authentication cookie, please try login again.


any solution?

Someone wrote that it was utf-8 problem, i dont know

**Comment by stmkjp** [comment]
@andybedoy  , 

check if your order data contains any of characters which cannot be converted with plain base64.encode functions.
(do console.log(this.state.order) in renderCheckout function in containers/Cart/index.js file)

And if so, modify the first line of renderCheckout function
from   ` const params = base64.encode(JSON.stringify(this.state.order));`
to `const params = base64.encode(encodeURIComponent((JSON.stringify(this.state.order))));`


I don't know if there's a better way but it worked.

**Comment by andybedoy** [comment]
thanks friend, its working for me!

**Comment by harry-harish** [comment]
help needed i followed every steps as defined here
1.installed mstore-checkout plugin
2.created "mstore-checkout" page with template page custom template

but in the app i get blank screen and when i see the network(inspector) it says 500
