### ISSUE TITLE
Checkout button not working !!

### ISSUE THREAD

**Issue by smdanishiqbal** [inspireui/mstore#142]
when i press confirm order  using a payment gateway its opens a inapp browser which says 404 page not found??
![27745097_1813673191996918_2133461506_o](https://user-images.githubusercontent.com/10116452/35746130-9850f6f8-0867-11e8-9e4a-642745534a59.png)

![27745070_1813673225330248_1871169900_o](https://user-images.githubusercontent.com/10116452/35746147-a8a035be-0867-11e8-9758-5fbc51e4629b.png)

Please Help to resolve this issue!!
Thanks.

**Comment by inspireui** [comment]
please see the response from - https://github.com/inspireui/mstore/issues/140
