### ISSUE TITLE
RTL issues 

### ISSUE THREAD

**Issue by techview51** [inspireui/mstore#143]
I added new Language to the app, and now, when I want to finalize the purchase, following error raises on the android device:

> **InvalidCharacterError: The string to be encoded contains characters outside of the Latin1 range**

I think it could be about "btoa". Need a solution ASAP. Thanks.

**Comment by inspireui** [comment]
This is related to https://github.com/inspireui/mstore/issues/114 - could you share your config.js file so that we have more data to test?

**Comment by techview51** [comment]
Maybe another way? It is not secure to publish API keys mentioned the config.js over the internet.

Some useful information:
1. Using the Arabic language (Added to Languages.js)
2. Products have Arabic names. 
3. The payment gateway is a local brand and has an Arabic name and description.
4. Currency symbol has UTF-8 characters.

**Comment by techview51** [comment]
@inspireui, Any good news?

**Comment by techview51** [comment]
Any hope? I can not use the product because if this error. Would you please solve this problem?

**Comment by techview51** [comment]
@inspireui Any solution? any reply? any action?

**Comment by inspireui** [comment]
Please try the Utf-8 solution from this ticket - https://github.com/inspireui/mstore/issues/140. Other RTL issues will be fixed on next version

**Comment by techview51** [comment]
@inspireui I tried that. Another problem raised: After choosing payment method, and going to next step, the app shows "Page not found".
Just for the record, I use a local payment gateway.
Solution please.
