### ISSUE TITLE
Stripe Payment shows 404 error in webview, even using mstore.io with default key in Config.js is error, And mstore.local shows "Can't get data from server."

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#144]
I am trying version pro 3.4.4

- My host with my consumer key in Config.js is 404 error in Stripe payment webview.
- mstore.local shows "Can't get data from server."
- mstore.io with default key in Config.js is error in Stripe payment, see below image.
<img src='https://image.prntscr.com/image/ZMbShDVWQK6WauVxMQUS_g.png'><img>

**Comment by minhcasi** [comment]
close as duplicate with issues/150
