### ISSUE TITLE
There is no "require('moments/locale/ar') "

### ISSUE THREAD

**Issue by techview51** [inspireui/mstore#146]
Hi,

First, The document addresses TimeAgo.js in `Components/Custom/react-native-timeago` but there is not such file. The correct path is `node_modules/react-native-timeago`.

Second, I did a hole search in the project(Pro) but did't find `require('moments/locale/ar')` as mentioned in the [document](https://beonews.inspireui.com/step-7-multi-languages.html).

Would you please help with this?
Thanks.

**Comment by inspireui** [comment]
please have a look to this screenshot - https://gyazo.com/a4a51ad39e888eb380d7516fad5f22da version 3.4.4

**Comment by techview51** [comment]
@inspireui , My problem was about BeoNews. Here is wrong place and sorry for that.
