### ISSUE TITLE
Wishlist with out of stock product 

### ISSUE THREAD

**Issue by melhendawy** [inspireui/mstore#148]
When you make a wishlist  from a out of stock products and open wishlist and press on add all to cart
All items added to the cart including the out of stock and the process completed to payment without any problem

**Comment by inspireui** [comment]
yeah, good point, we may add more validate on this case - thank you!

**Comment by inspireui** [comment]
Noted, move to ticket support please move to https://inspireui.ticksy.com/ - Thank you !
