### ISSUE TITLE
Sharing document: installing on window

### ISSUE THREAD

**Issue by alien3d** [inspireui/mstore#15]
this apply to version 3.1  

[Android.pdf](https://github.com/inspireui/mstore/files/1151946/Android.pdf)

**Comment by inspireui** [comment]
Thank you so much for the sharing, we are released new v3.2 and it will be available soon on next 1-2 days.

**Comment by alien3d** [comment]
success  install v 3.2.1 in weird way using OS X and android.. later will try using Xcode..  later i document everything..

**Comment by HamzaDevZubair** [comment]
**I am getting admob error, I am using latest Mstore 3.2.1 version**

![wdw](https://user-images.githubusercontent.com/27667777/28355096-061d1276-6c7c-11e7-8b0f-03f4d68b2f7e.PNG)

**Comment by alien3d** [comment]
try yarn remove react-native-admob and then  yarn add react-native.   I yet test the windows version but doing some testing on iOS OS X..

**Comment by HamzaDevZubair** [comment]
Thanks mate

**Comment by suhendranst** [comment]
I've tried yarn remove react-native-admob and then yarn add react-native-admob
but there was an error like this picture : 

![gambar](https://user-images.githubusercontent.com/37798795/37900690-306f0a9a-3119-11e8-89bb-db324b32de58.png)
![screenshot_14](https://user-images.githubusercontent.com/37798795/37900740-4ac2dcb4-3119-11e8-8739-7b8a153ba4f0.jpg)

**Comment by inspireui** [comment]
@suhendranst - could you try to update the android/app/build.grade

`    compileSdkVersion 23
    buildToolsVersion "23.0.1"
`

And change to 

`    compileSdkVersion 26
    buildToolsVersion "26.0.2"
`

**Comment by suhendranst** [comment]
does not work for me

**Comment by suhendranst** [comment]
![screenshot_15](https://user-images.githubusercontent.com/37798795/38018939-8979a4a0-32a0-11e8-9f82-e1c6ec657562.jpg)
What is wrong ?

**Comment by inspireui** [comment]
Could you upgrade the abmod library to 2.0.0-beta.3 (edit from package.json)

**Comment by suhendranst** [comment]
before my admob package is already in version to 2.0.0-beta.3
