### ISSUE TITLE
Stripe payment is error in iOS Expo Demo.

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#150]
Stripe payment is error in iOS Expo Demo, while other payment option looks good.
<img src='https://image.prntscr.com/image/H_XihVl-QHqvRBAf-AWHMg.png'></img>

**Comment by inspireui** [comment]
thank you, we are checking and will have an update

**Comment by minhcasi** [comment]
Hi, please try to update the mstore-checkout to fix this issue - https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout 

Thank you!

**Comment by inspireui** [comment]
Hi, you can re-install the mstore-checkout then it will be fixed on your site - https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout

**Comment by lin-zy1229** [comment]
Hello~!!!
Please read my description carefully.
I am trying your demo "mstore.io", not my site (mstore.local nor my host).
