### ISSUE TITLE
Product types

### ISSUE THREAD

**Issue by Brdnn** [inspireui/mstore#151]
Hi, some of my woocommerce products are External/Affiliate product which after clicking the "Buy Now" button will redirect the customer to another link for checkout. Can I know how can I edit the product types in this app?

**Comment by inspireui** [comment]
Hi, you can refer to this document to get the product detail - https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

You may need to customize the API to return require affiliate link for your product, or could be the extra plugins that build by that services

**Comment by Brdnn** [comment]
May I know where should I change the API? in wordpress or in the app file?

**Comment by inspireui** [comment]
From the app, you can update it form config.js file

**Comment by Brdnn** [comment]
I don't know how to change the API return for affiliate link :(

Besides, for the links in single news page is not clickable.
