### ISSUE TITLE
Application takes time to load products

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/mstore#153]
When the user first time loads up the application, it takes approximately 15 seconds to load all the products in the dashboard section. How can I reduce this time frame?

**Comment by inspireui** [comment]
Hi, you can use turn this option to optimize the image loading:

// file config.js 
ProductSize: {
    enable: true,
    CatalogImages: {width: 348, height: 445},
    SingleProductImage: {width: 568, height: 725},
    ProductThumbnails: {width: 78, height: 99},
  },

And make sure the product size match with your setting from the website, please refer to https://mstore.gitbooks.io/mstore-manual/content/chapter5.html the product display size.
