### ISSUE TITLE
Checkout Takes too much time to load in webview!!!

### ISSUE THREAD

**Issue by smdanishiqbal** [inspireui/mstore#154]
After clicking checkout button its open webview where it takes approx. 15sec to load payment gateway details. it very confusing for users.?any Solution?

**Comment by inspireui** [comment]
Hi, could you review from your website performance and enhance the loading time, also try to unload the un-use JS file that load the the payment screens, this could be done by customize the plugins (mstore-checkout). 

P/S: From the plugin, we load all JS as default to support Stripe payment for the demo

**Comment by smdanishiqbal** [comment]
@inspireui  will u please mention the file name in which JS for stripe support is declared in  mstore-checkout plugin?

**Comment by inspireui** [comment]
You can customize this plugin file - https://github.com/inspireui/mstore/blob/master/plugins/mstore-checkout/mstore-checkout.php
