### ISSUE TITLE
News menu issue - hope,twoColum,threeColumn,Card,etc..Flatlist need getItemLayout‘s props,

### ISSUE THREAD

**Issue by z5614036** [inspireui/mstore#155]
there are many bug for no getItemLayout props to Flatlist

**Comment by z5614036** [comment]
fetch more data, if e.nativeEvent.ContentSize.height more than 8000 ,bug must be appearance;

**Comment by inspireui** [comment]
Hi, we will have a check and improve the Flatlist for News section - thank you!

**Comment by z5614036** [comment]
![20180224181043](https://user-images.githubusercontent.com/24545834/36629221-f8da4d4e-198d-11e8-8ebd-2e48899f2d78.jpg)

**Comment by z5614036** [comment]
after install plugin,everything is going wrong

**Comment by z5614036** [comment]
![20180224181242](https://user-images.githubusercontent.com/24545834/36629236-3d5369ec-198e-11e8-85f9-e31c5c343a11.jpg)

**Comment by inspireui** [comment]
Hi, could you check the guide from here - https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout/wp-templater

It cause by import the wp-templaer from mstore-checkout line 64
Could be and issue with your PHP version - thank you!

**Comment by z5614036** [comment]
my php version should be 7.2.2，use xampp 3.2.2version

**Comment by inspireui** [comment]
pls download the latest version 3.4.5 will be fixed this issues - thank you!
