### ISSUE TITLE
Splashscreen and home 

### ISSUE THREAD

**Issue by andybedoy** [inspireui/mstore#156]
splashscreen and home does not show the products horizon layout i followed all the instructions and continues without fixing and i  reviewed this arrangement and it's done

https://mstore.gitbooks.io/mstore-manual/content/chapter6.html

https://github.com/inspireui/mstore/issues/81

**Comment by andybedoy** [comment]
I managed to solve the home, it turns out that in the documentation do not explain that the number id of the category is in the url of woocommerce, what happend with splashscreen any solution?

**Comment by andybedoy** [comment]
i resolve the page contact and home only need splashscreen and intro app or onboard after enter to app

**Comment by lin-zy1229** [comment]
I've splashscreen issue, too.
My issue is:

> It seems good until home screen loaded. (Splash screen displayed)
> But no more responsible for any toolbar buttons and menu button on Home Screen (Shop Screen), except only scrolling up/down.
> And after a while, app crashed with OutOfMemory exception.

I resolved it by modifying following code:
#### File: \src\containers\SplashScreen\index.js

```
... ...
var prepared = false; // added line
class SplashScreen extends Component {
... ...
  prepareData() {
    if(prepared) return;  // added line
    prepared = true;  // added line
... ...
    let resetData = {
          index: 0,
          key: null, // added line
          actions: [NavigationActions.navigate({routeName: 'HomeScreen'})]
    };
... ...
```
However, I don't know why I should do this.
Please explain me what the exact way is to solve this issue.

**Comment by mayankgirdhar** [comment]
i have a splash screen not showing problem please help and when will you give next update please tell us.

**Comment by andybedoy** [comment]
continue dont work, please fixed this error be cause the app without splashscreen is very bad

**Comment by lin-zy1229** [comment]
@mayankgirdhar, Sorry, I was using 3.3.3

**Comment by andybedoy** [comment]
@lin-zy1229 you can pass me the previous version you have 3.3.3 please? my email is gerenciadongato@gmail.com

**Comment by inspireui** [comment]
@lin-zy1229 @andybedoy you can use this lib for the Stripe native payment - https://github.com/tipsi/tipsi-stripe - the reason we replace this lib is it trouble for most user when installing and not dynamic as Webview although the UX is better

**Comment by mayankgirdhar** [comment]
@andybedoy @lin-zy1229 @inspireui guys i don't need stripe payments just need cash on delivery. is 3.3.4 only has webview payment if yes how can i download 3.3.3 version?

**Comment by inspireui** [comment]
fixed

**Comment by lin-zy1229** [comment]
@mayankgirdhar request to developer.

**Comment by lin-zy1229** [comment]
@inspireui could you please post the fixed part code here? Because I am using lower version of your source and I customized it lots.
