### ISSUE TITLE
Login screen shows every time in Cart Screen even once login success. 

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#157]
### Reproduction Error
I would do this action.
* Launch app and go to shop (not login)
* Go cart or buy any product
* Click 'Next Step' in Cart Screen.
* It will show Login screen, and do login.
* it will be back to Cart screen automatically once login success.
* Try to click 'Next Step' Button again.

This action succeed only once.
Well, try to logout, and go to Cart screen, and repeat above steps again.

Then, it will show Login screen again.
Very annoying.
To avoid this, I had to do only login from Side Menu.

**Comment by andybedoy** [comment]
me too i have this problem

**Comment by levi-beers** [comment]
Do you have the Wordpress plugins "JSON API, JSON API AUTH and Mstore Checkout" installed and activated? You must also have "Anyone can register" option enabled with Wordpress. Last, ensure the WooCommerce API Key/Secret is correct.

**Comment by lin-zy1229** [comment]
@levi-beers, Please note that login has been done successfully.

**Comment by inspireui** [comment]
Hi @lin-zy1229 could you try to install Reactotron - https://mstore.gitbooks.io/mstore-manual/content/chapter2.html then check the return Json when processing login is success or not, could be and issue with authentication on your site - thank you!

**Comment by andybedoy** [comment]
when compiling, the changes in the physical device are not displayed, they only work in the virtual

**Comment by lin-zy1229** [comment]
Hi @inspireui , if it is the issue with authentication on my site, how can the login in Slide menu's Login Menu succeed? Could you please explain it?

**Comment by andybedoy** [comment]
same error, login in first time well, close session and try again to start and do not login, error with facebook login

**Comment by andybedoy** [comment]
in the virtual device does not generate that problem

**Comment by lin-zy1229** [comment]
Same in the simulator in my case.

**Comment by andybedoy** [comment]
i continue with this error
