### ISSUE TITLE
Bug: WooCommerce Order Notifications Not Being Sent - Cash Payment Option

### ISSUE THREAD

**Issue by levi-beers** [inspireui/mstore#160]
I've noticed that the order notifications which are sent to the site admin and the user when an order is placed do not happen when an order is submitted via the mobile app. Any idea on how to resolve this?

**Comment by inspireui** [comment]
Hi @levi-beers could i know the order is made with COD or payment gateway, please try to change the "payment status" on the app and make sure it is enable to allow send notification from the Wordpress site (with that status)
