### ISSUE TITLE
Coupon Bugs: 1) Cannot checkout with Coupon + Cash Payment & 2) Wrong coupon calculation

### ISSUE THREAD

**Issue by levi-beers** [inspireui/mstore#162]
1) When I try to checkout using a coupon and the cash payment option, the app comes back "Invalid Parameter(s): coupon_lines"

2) I created a 5 dollar off coupon and the system applied the code, but gave a 5 percent discount instead. It should detect whether it's a percentage or a monetary amount.

**Comment by shamstarek** [comment]
I have the same for the first issue, Any help?

**Comment by shamstarek** [comment]
Any update?

**Comment by inspireui** [comment]
Fixed,

Try to change to coupon to array (this worked before but it is changed by latest API)

`return [{
        code: couponCode,
      }]`

<img width="840" alt="screen shot 2018-03-28 at 6 41 09 pm" src="https://user-images.githubusercontent.com/29778334/38026783-a37edebc-32b7-11e8-8304-acabb0565a6c.png">
