### ISSUE TITLE
iOS Build Error in Stripe.h

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#163]
<img src="https://i.imgur.com/bJZIdmd.png">

../../../ios/Pods/Headers/Public/Stripe/Stripe.h:1:1: error: expected identifier or '('

**Comment by lin-zy1229** [comment]
I fixed it by downloading and installing FBSDK into `~/Documents/FackbookSDK` directroy.

**Comment by inspireui** [comment]
Thank you!
