### ISSUE TITLE
Delete button disappeared in Cart Page.

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#164]
It is okay when app runs first.

Well, when I close the app completely by removing in apps stacks, remaining some products in cart, and relaunch the app, then I can't remove any product by swiping left, because red DELETE button disappeared.
***Now the only way to get rid of it is to buy out all of items pending or delete the app and reinstall it.***
Very big issue for me.
<hr>
<img src="https://i.imgur.com/dfauz9K.png" />

**Comment by inspireui** [comment]
Thanks @lin-zy1229 we are trying to replicate it, could i know it is test on which Android version ?

**Comment by lin-zy1229** [comment]
Android 7.0 (API 24)

**Comment by lin-zy1229** [comment]
Hope this issue to be resolved quickly. and I am very regret to know this app has lots issues.

**Comment by inspireui** [comment]
Hi, we've replicated it and fixing the issue - thanks

**Comment by lin-zy1229** [comment]
Please send me the solution.

**Comment by lin-zy1229** [comment]
you do not share the solution?

**Comment by inspireui** [comment]
response and send package to your email, basically you can reinstall this library to fix the problem - https://github.com/jemise111/react-native-swipe-list-view

**Comment by lin-zy1229** [comment]
Hello, what do you mean 'reinstall' ?
I am using already latest version of it.

**Comment by inspireui** [comment]
the project is using 0.4.7, if you update to latest v1.0.6 then you need to check if the format is change or something else, try to use their example

**Comment by lin-zy1229** [comment]
Hello, please just explain why it works not.
It worked at the first, and just doesn't work when relaunch with remaining products in Cart.
I think this issue hasn't relation with 'react-native-swipe-list-view' dependency.
Hope your kind explanation, and more reasonable suggestion.

**Comment by lin-zy1229** [comment]
It doesn't work.

**Comment by inspireui** [comment]
so please try to use the remove button instead of the swipe-list-view on this lib or using other library like this one - https://github.com/dancormier/react-native-swipeout

**Comment by lin-zy1229** [comment]
I re-wrote the code thoroughly using react-native-swipeout, and resolved this issue.
