### ISSUE TITLE
Login error Unkonw controller 'mstore_user'

### ISSUE THREAD

**Issue by Sherif-Magdy** [inspireui/mstore#166]
Hi,

I've an error in user login.
Firstly I installed & actives all required plugins.

The error message is: "Unknown controller 'mstore_user'"

**Comment by lin-zy1229** [comment]
Why don't you install mstore-checkout plugin in your wordpress?

**Comment by shamstarek** [comment]
I have the same issue.
the installed plugins are:
1- mstore-checkout	
2- json-api-auth	
3- json-api	
4- better-rest-api-featured-images	
5- regenerate-thumbnails

But when I test the API call, it back an error message:
/api/mstore_user/generate_auth_cookie/
{
  "status": "error",
  "error": "Unknown controller 'mstore_user'."
}

I'm using php ver 7.1
Can you help me please?

**Comment by lin-zy1229** [comment]
@shamstarek , please install "Mstoreapp Mobile App" plugin, and check if you installed "Mstore CheckOut Plugin and API" plugin.

**Comment by shamstarek** [comment]
Thanks @lin-zy1229 
Mentioned plugin "https://wordpress.org/plugins/woo-mstoreapp-mobile-app/" just installed and activated.
Then I generate a new api key and set consumer & secret key in WordPress->Mobile App.

But the issue still exists.
Any help?

**Comment by lin-zy1229** [comment]
@shamstarek , What is your mstore-pro version ?

**Comment by shamstarek** [comment]
@lin-zy1229 3.4.4

**Comment by shamstarek** [comment]
@lin-zy1229 Yes, fixed.
Many Thanks

**Comment by lin-zy1229** [comment]
@shamstarek , it is strange you voted and removed soon.
