### ISSUE TITLE
How to Add new Product Category in menu and Blog Category  in sidebar

### ISSUE THREAD

**Issue by smdanishiqbal** [inspireui/mstore#167]
I want to add a product category in left menu through which user can view special offer etc and i also need a blog category menu .
![screenshot_20180313-170840](https://user-images.githubusercontent.com/10116452/37351216-627a9ee0-26fc-11e8-921d-373a5ff8bc76.jpg)

**Comment by inspireui** [comment]
Noted you idea, we will consider to update on later version - thank you!

**Comment by inspireui** [comment]
already support on latest Mstore version
