### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by gaboelnuevo** [inspireui/mstore#168]
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Invalid version: "3.4"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Documents/mstore-v3.4.4/mstore-expo/npm-debug.log

**Comment by gaboelnuevo** [comment]
Resolved editing package.json

**Comment by inspireui** [comment]
Thank you!
