### ISSUE TITLE
[BEONEWS] Can't run the project ?

### ISSUE THREAD

**Issue by leiluspocus** [inspireui/mstore#169]
Hi

I tried to run the install and I'm having a weird issue after the app has bundled. 

![capture d ecran 2018-03-14 a 12 35 30](https://user-images.githubusercontent.com/1473845/37400169-53ab834c-2784-11e8-91ae-f41ba3a17c3b.png)

I followed the steps mentioned here for the dependencies: https://beonews.inspireui.com/step-1.html I managed to run succesfully a basic react native app. And I'm still plugged to the beonews wordpress ( http://news.inspireui.com/ this wordpress )

I tried to clear all the caches using this command: 
> npm cache clean && watchman watch-del-all && rm -rf node_modules && npm install && npm start -- --reset-cache 

Am I missing something ? 

Cheers

**Comment by lin-zy1229** [comment]
Are you working with mstore-pro or what?

**Comment by leiluspocus** [comment]
I bought the theme Beonews Pro on CodeCanyon ( https://codecanyon.net/item/beonews-react-native-mobile-app-for-wordpress/19186520 )

**Comment by lin-zy1229** [comment]
I recommend you please don't use their products.
not ready to release at all.

**Comment by inspireui** [comment]
Hi, could you help to check 2 issues:
1. The facebookSDK is download and copy to Documents, base on this guide - https://beonews.inspireui.com/beonews-setup.html

2. Please open the XCode and run the project from there, then send us the detail log screenshot when click to the 'red warning icon' 

Thank you!

**Comment by inspireui** [comment]
you can try to see if can work on cmd:
`yarn start --reset-cache
react-native run-ios`

There is no issues with the warning message as most of them is come from the library and also form react native core library

**Comment by leiluspocus** [comment]
I have an other error.

![capture d ecran 2018-03-15 a 15 28 17](https://user-images.githubusercontent.com/1473845/37469450-968e2bc4-2865-11e8-9fce-ef2f0f770757.png)

**Comment by inspireui** [comment]
Hi, could you try to tag some post, looks like your Wordpress don't have the tag so it is returned empty - thank you!

**Comment by inspireui** [comment]
pls try to create ticket in https://inspireui.ticksy.com if you still have an issues - thank you!
