### ISSUE TITLE
Splash screen in iOS

### ISSUE THREAD

**Issue by lin-zy1229** [inspireui/mstore#170]
It doesn't work.
It shows twice while launching app.
First screen, is Mstore splash, and 2nd screen is My custom splash, and 3rd screen is Home screen.
I replaced both of 2 images same, in src/images/splash_screen.png file and ios\beostore\Images.xcassets\splash_screen.imageset\splash_screen.png.

But still MStore splash screen shows. even I confirmed the view of beostore/LaunchScreen.xib in Xcode.
And I tried to clean and rebuild in Xcode project.

Just wonder where the mstore splash screen comes.

Any solution?
- remove duplicated splash screen showing in iOS.
- and apply of custom splash screen as LaunchScreen.xib itself.

**Comment by minhcasi** [comment]
not supported

**Comment by lin-zy1229** [comment]
Not supported? then, All customers should use your mstore splash image?

**Comment by inspireui** [comment]
You can go to images/splash_screen.png to replace this image and open Xcode to replace it here - https://gyazo.com/9ef1525783b87d18a7ca31b88f594b86 Thanks

**Comment by lin-zy1229** [comment]
Thanks, @inspireui , however, didn't you read my description carefully?

>  I confirmed the view of beostore/LaunchScreen.xib in Xcode.

Very sorry for your rough support.

**Comment by inspireui** [comment]
Thanks @lin-zy1229 

Pls don't try to give some comment like this - https://gyazo.com/f229cdf957ce6d80c20e8650c6967cf2 if you would like to get our further support - thank you!

**Comment by lin-zy1229** [comment]
Is this the answer for this issue?

**Comment by inspireui** [comment]
You can remove the custom splash and use LaunchScreen.xib for change the splash screen

**Comment by lin-zy1229** [comment]
Hello, what is the custom splash? I never added anything there.
Just replaced only splash image.
I meant just custom splash image.

**Comment by inspireui** [comment]
Try to send you whole custom package to our support email support@inspireui.com - we will help to check the splash screen issue

**Comment by lin-zy1229** [comment]
HELLO, no any custom package here~!!!

**Comment by inspireui** [comment]
i mean the whole source code code you are having trouble with this splash screen, zip it and share the link via Dropbox - thanks !
