### ISSUE TITLE
Unable to get started with MStore Expo 

### ISSUE THREAD

**Issue by ganesh742211** [inspireui/mstore#171]
Iam new to react native..so just brought this template .. but facing some issues..
can anyone help me.. below is the code from cmd 

C:\mstore-v3.4.4-expo\mstore-expo>yarn install
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.87s.

C:\mstore-v3.4.4-expo\mstore-expo>yarn start
yarn run v1.5.1
error An unexpected error occurred: "Command \"start\" not found.".
info If you think this is a bug, please open a bug report with the information provided in "C:\\mstore-v3.4.4-expo\\mstore-expo\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\mstore-v3.4.4-expo\mstore-expo>npm start
npm ERR! Invalid version: "3.4"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2018-03-21T19_38_31_513Z-debug.log

C:\mstore-v3.4.4-expo\mstore-expo> react-native run-android
Scanning folders for symlinks in C:\mstore-v3.4.4-expo\mstore-expo\node_modules (58ms)
Android project not found. Maybe run react-native android first?

**Comment by inspireui** [comment]
Hi, regarding to the mstore expo, you could not run by yarn start.

Try to open the Expo XDE and run from there or using the expo cmd: 
exp start
exp ios
