### ISSUE TITLE
phone number ( Constraints )

### ISSUE THREAD

**Issue by xa9** [inspireui/mstore#172]
if a customer write 8 numbers in checkout page , see screenshot :
![edfge](https://user-images.githubusercontent.com/29809274/37859561-9f1752bc-2f26-11e8-9c2f-78a7d24acd39.png)

how to edit it to 8 number ? 
![sdf](https://user-images.githubusercontent.com/29809274/37859572-d43760d6-2f26-11e8-88b1-b0820db16d10.png)

**Comment by shamstarek** [comment]
Did you try to start phone number with 'zero'?

**Comment by xa9** [comment]
No , in my country the phone number starts from numbers 9 or 6 or 5 dependent on carrier .

**Comment by inspireui** [comment]
pls try with `^([569]{1})([0-9]{7})`

example: https://regexr.com/3msth

**Comment by xa9** [comment]
its work now

thanks for help :)

**Comment by inspireui** [comment]
@xa9 pls give us a good rating (http://codecanyon.net/downloads) if the product is help for your business - thank you!
