### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by joelshotton** [inspireui/mstore#173]
Hi I'm getting this error when I run the android build "react-native run-android"

* What went wrong:
Execution failed for task ':react-native-admob:processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

I believe I have followed the set up instructions correctly and I can run a starter react native app on android.

react-native info

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.10.1
  Yarn: 1.5.1
  npm: Not Found
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

$ $ANDROID_HOME/tools/bin/sdkmanager --list

Installed packages:=====================] 100% Computing updates...             
  Path                                                                              | Version | Description                                     | Location                                                                          
  -------                                                                           | ------- | -------                                         | -------                                                                           
  add-ons;addon-google_apis-google-23                                               | 1       | Google APIs                                     | add-ons/addon-google_apis-google-23/                                              
  build-tools;23.0.1                                                                | 23.0.1  | Android SDK Build-Tools 23.0.1                  | build-tools/23.0.1/                                                               
  build-tools;24.0.3                                                                | 24.0.3  | Android SDK Build-Tools 24.0.3                  | build-tools/24.0.3/                                                               
  build-tools;25.0.0                                                                | 25.0.0  | Android SDK Build-Tools 25                      | build-tools/25.0.0/                                                               
  build-tools;25.0.3                                                                | 25.0.3  | Android SDK Build-Tools 25.0.3                  | build-tools/25.0.3/                                                               
  build-tools;26.0.1                                                                | 26.0.1  | Android SDK Build-Tools 26.0.1                  | build-tools/26.0.1/                                                               
  emulator                                                                          | 27.1.12 | Android Emulator                                | emulator/                                                                         
  extras;android;m2repository                                                       | 47.0.0  | Android Support Repository                      | extras/android/m2repository/                                                      
  extras;google;google_play_services                                                | 48      | Google Play services                            | extras/google/google_play_services/                                               
  extras;google;m2repository                                                        | 58      | Google Repository                               | extras/google/m2repository/                                                       
  extras;google;market_licensing                                                    | 1       | Google Play Licensing Library                   | extras/google/market_licensing/                                                   
  extras;intel;Hardware_Accelerated_Execution_Manager                               | 6.2.1   | Intel x86 Emulator Accelerator (HAXM installer) | extras/intel/Hardware_Accelerated_Execution_Manager/                              
  extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2 | 1       | Solver for ConstraintLayout 1.0.2               | extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/
  extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2        | 1       | ConstraintLayout for Android 1.0.2              | extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/       
  patcher;v4                                                                        | 1       | SDK Patch Applier v4                            | patcher/v4/                                                                       
  platform-tools                                                                    | 27.0.1  | Android SDK Platform-Tools                      | platform-tools/                                                                   
  platforms;android-23                                                              | 3       | Android SDK Platform 23                         | platforms/android-23/                                                             
  platforms;android-25                                                              | 3       | Android SDK Platform 25                         | platforms/android-25/                                                             
  platforms;android-26                                                              | 2       | Android SDK Platform 26                         | platforms/android-26/                                                             
  platforms;android-27                                                              | 1       | Android SDK Platform 27                         | platforms/android-27/                                                             
  sources;android-23                                                                | 1       | Sources for Android 23                          | sources/android-23/                                                               
  sources;android-25                                                                | 1       | Sources for Android 25                          | sources/android-25/                                                               
  sources;android-26                                                                | 1       | Sources for Android 26                          | sources/android-26/                                                               
  system-images;android-23;default;x86_64                                           | 10      | Intel x86 Atom_64 System Image                  | system-images/android-23/default/x86_64/                                          
  system-images;android-23;google_apis;x86_64                                       | 26      | Google APIs Intel x86 Atom_64 System Image      | system-images/android-23/google_apis/x86_64/                                      
  system-images;android-25;android-wear;x86                                         | 3       | Android Wear Intel x86 Atom System Image        | system-images/android-25/android-wear/x86/                                        
  system-images;android-25;google_apis;x86_64                                       | 11      | Google APIs Intel x86 Atom_64 System Image      | system-images/android-25/google_apis/x86_64/                                      
  tools                                                                             | 26.1.1  | Android SDK Tools                               | tools/

**Comment by inspireui** [comment]
Hi, pls download the latest 3.4.5 to fix this issue - thank you!
