### ISSUE TITLE
Error when installing mstore_checkout plugin - Fatal error: Cannot declare class Mobile_Detect, because the name is already in use in /var/www/html/wp-content/plugins/mstore-checkout/templates/class-mobile-detect.php on line 28

### ISSUE THREAD

**Issue by albertkim** [inspireui/mstore#177]
![image](https://user-images.githubusercontent.com/5528625/38966704-6fbe7560-4338-11e8-85cb-828b8f497bbb.png)

Fatal error: Cannot declare class Mobile_Detect, because the name is already in use in /var/www/html/wp-content/plugins/mstore-checkout/templates/class-mobile-detect.php on line 28

I have all other mstore plugins installed, and this is the last one that just won't install correctly. What could this error be referring to?

**Comment by Sam-Hoult** [comment]
The `class Mobile_Detect` should be wrapped in: `if ( !class_exists('Mobile_Detect') ) {}` to avoid conflicts
