### ISSUE TITLE
Fatal error after installed "mstore-checkout" plugin, details inside

### ISSUE THREAD

**Issue by iWolfgang** [inspireui/mstore#178]
Dear inspireUI team,

Running WordPress on local environment, after installed "mstore-checkout" plugin I received Fatal error as shown in the attached picture.

Thanks a lot,

Wolfgang

![wechatimg322](https://user-images.githubusercontent.com/5768583/39124835-7e0eb9a4-472f-11e8-94bb-3c98dc3ea937.png)

**Comment by inspireui** [comment]
supported

**Comment by iWolfgang** [comment]
Many thanks, saw your reply on Ticksy.
Great team.
