### ISSUE TITLE
Posts not being load correctly

### ISSUE THREAD

**Issue by mtsdnz** [inspireui/mstore#182]
**Home Screen** posts issue:
1. If I click on the Category filter and select some category, it doesn't update the List, but if I click again, and select the same filter, it updates. 

2. If I go to the category page and click on some category, when I come back to the home screen, it shows only the posts from the category that I clicked previous. But if I update the page(scrolling down), it shows all the posts again.

**Category Screen** posts issues:

1. Sometimes, when I click on a category and then go back to the category page, and click in another, it also shows the posts from the previous category(the one that I clicked before). If I refresh the page, the posts are loaded ok.

Also, when I open the debug console, there's a lot of errors with this message:

> Warning: `flexWrap: `wrap`` is not supported with the `VirtualizedList` components.Consider using `numColumns` with `FlatList` instead.

**Comment by mtsdnz** [comment]
Another issue that I found today:
If I go to the Category's page, and click on a category, it will load the category posts correctly. Now, if I go to the Home page again, update the posts(scrolling down) and come back to the category tab, it shows the posts from the home page, instead of the posts from the category.

**Comment by inspireui** [comment]
Please download the latest v3.5.8 for the fixed, and try to follow up to our support ticket https://inspireui.ticksy.com/ - Thank you !
