### ISSUE TITLE
the app performance

### ISSUE THREAD

**Issue by adnannidal** [inspireui/mstore#2]
Hey guys can you please check the video below the see why the app performance is very poor ??

https://drive.google.com/file/d/0ByynV4zah1bqd09XY0Q5U3ZKeUE/view?usp=sharing

-the color variant is not showing up
-only the first product image is showing the rest is only a blank
-the app is very very slow and keep freezing.

i don't know whats wrong ???

please advise

**Comment by inspireui** [comment]
Hi, could you download the latest version v3.1 from Envato which has just released on today to see if it is faster?

**Comment by adnannidal** [comment]
v 3.1 is not available on Envato, i only can see version v 3.0

**Comment by inspireui** [comment]
Hi Adnan, thank you for your checking, i've sent the latest package to your email to check if it better.

**Comment by faysal515** [comment]
I also don't see any v3.1 download options. It downloads the previous version. purchase_Id: faysal515

**Comment by inspireui** [comment]
Hi faysal515, i'm checking with Envato about the review code and we may submit the update again, in the meantime please send your request download new version to our email support@inspireui.com with the purchase code.

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 is more stable and good performance now. Thank you for your feedback.
