### ISSUE TITLE
Issue with product appearance 

### ISSUE THREAD

**Issue by Sherif-Magdy** [inspireui/mstore#21]
I have an issue where 10 products keep repeating on the home screen as well as within each category screen. At the end of each screen, the same 10 products reappear instead of having the next group of products.

I am also getting this warning message:                        

- Warning: flattenChildren(...): Encountered two children with the same key. Child keys must be unique; when two children share a key, only the first.

**Comment by inspireui** [comment]
Hi, thank for reporting, we will check this issue and get back to you soon.

**Comment by Sherif-Magdy** [comment]
@inspireui 
Hi, do you have any updates regarding My issue?

**Comment by inspireui** [comment]
Yes, we will update new release on next week to fix this issue and some minor bug fixed. Thank you

**Comment by Sherif-Magdy** [comment]
@inspireui 
Thank you

**Comment by Sherif-Magdy** [comment]
Hi @inspireui , iam still waiting to resolve this issue iam having with the app. when will the update be released?

**Comment by inspireui** [comment]
Hi @Sherif-Magdy sorry for the delay as we have some issue with the resource, we are set it as higher priority and fixing it on around this week. Thank you!

**Comment by mustymx** [comment]
Hi @Sherif-Magdy, I have the same problem, have you solved it?

**Comment by inspireui** [comment]
Hi, it could be related to the local storage issues, please try with: Simulator/Reset content and settings to reset the local data and test it again. 

If you still have and issue on your website please share your Constants file to our support email support@inspireui.com. We will help to have a check. Thank you!

**Comment by Sherif-Magdy** [comment]
Hi @mustymx, no I have not resolved the issue yet but if you find a solution or have any updates please let me know.

**Comment by iva-kz** [comment]
Hi @inspireui, I have the same issue with products not updating. Do we have to expect a new version soon?

**Comment by inspireui** [comment]
we're going to release the product today, you can check the demo of new version from - https://expo.io/@minhcasi/mstore

**Comment by mustymx** [comment]
in this demo the keyboard does not respond properly, cover the form fields. or maybe the scrollview function does not work on the forms (login, checkout, etc.)

**Comment by inspireui** [comment]
Hi @mustymx can i know your device testing, it is iOs or Android OS ?

**Comment by inspireui** [comment]
Hi @Sherif-Magdy could you check if this issue is fixed on v3.3, kindly close if you are happy with the fix. Thank you!

**Comment by mv-developer** [comment]
Hi @inspireui ,
i have the same issue and still not working in new release v 3.3
