### ISSUE TITLE
_reactNativeAdmob.AdmobInterstitial.setAdUnitID is undefined

### ISSUE THREAD

**Issue by pavilion016** [inspireui/mstore#23]
when I run it show red screen and _reactNativeAdmob.AdmobInterstitial.setAdUnitID is undefined

<img width="375" alt="screen shot 2560-07-22 at 8 16 10 pm" src="https://user-images.githubusercontent.com/291803/28491396-d194473a-6f1a-11e7-961f-eaff9a53cf64.png">

**Comment by inspireui** [comment]
Is it happing on the default constants.js config file, please share your config file to our support email so that we can help to check your case. Thanks

**Comment by pavilion016** [comment]
I did't change anything  in config files.

**Comment by pavilion016** [comment]
so how can i do ??

**Comment by inspireui** [comment]
We could not replicate this issue on our Mac Os, could you help to download the latest version v3.2.1 and make a video screenshot ?

**Comment by pavilion016** [comment]
3.2.1 of what ?

**Comment by inspireui** [comment]
Hey sorry, as you raise the ticket in wrong project so we though you have reported for mstore v.3.2, this ticket should be in - https://github.com/inspireui/beonews/issues

**Comment by pavilion016** [comment]
sry but you give this link to me in  codecanyon
![chrome_2017-07-26_12-20-49](https://user-images.githubusercontent.com/291803/28605664-168fc58c-71fd-11e7-8149-e61711f83e14.png)

**Comment by inspireui** [comment]
oh, sorry, it's my fail 😭 . Could you help to quick take the video screenshot your issues pls ?

**Comment by pavilion016** [comment]
https://github.com/inspireui/beonews/issues/10

here for my problem video.

**Comment by inspireui** [comment]
please check with latest version v3.3.2 to fix the issue. Thank you!
