### ISSUE TITLE
Product Image not showing on the APP

### ISSUE THREAD

**Issue by hazephase** [inspireui/mstore#25]
After installing the new version, the product images are not showing nor are the product details.

**Comment by xa9** [comment]
+1

Pls help..!

**Comment by inspireui** [comment]
Closed as duplicate with #18. 

@hazepha please check your email to see the solution
The fixing is just ignore the resize image as your image URL is not work, example hosting/wp-content/uploads/2016/12/IMG_9202-1000x1000.jpg so you can use original image like - host/wp-content/uploads/2016/12/IMG_9202.jpg, by this update on Omni.js
<code>
export const getProductImage = (uri, containerWidth) => {
    return uri;
</code>

**Comment by hazephase** [comment]
`export const getProductImage = (uri, containerWidth) => { return uri;  `  should I take out the full function? or just the one line?

**Comment by inspireui** [comment]
just return uri, i've sent the attache to your email, pls check
