### ISSUE TITLE
Stuck in the payment page

### ISSUE THREAD

**Issue by xwr870312** [inspireui/mstore#27]
I have a problem when i tried to pay using Stripe and Paypal: i stuck in the payment page (i should see a thank you page) after i filled out the payment details by Stripe. Paypal just kept kicking me out the app when i choose it as my payment method. Could you please help me with it? Very appreciated!

**Comment by inspireui** [comment]
Looks like i have just response to your email, could you help to enable the Debug mode then send us the detail crash issue, please let us know  which Pro or Expo version and your OS ?

**Comment by xwr870312** [comment]
Thanks for your reply. Just wondering how can i enable the Debug mode? im using Pro version and it's running on IOS.

**Comment by xwr870312** [comment]
Thanks for your reply. I turned on reactotron when i ran the app. And i found this when i stuck in the payment page:

API response
http://meifan.com.au/payment
Status Code
404
Method
POST
Duration (ms)
1425

Do you know how to fix this? BTW, what should i put in for serverURL for stripe in constants.js?
Do you think that's the reason cause this issue?

**Comment by inspireui** [comment]
Hi could you check you Paypal setting from your paypal account - https://gyazo.com/c356eba0b495af82bde915a70f3078a2 
https://gyazo.com/d60280916700a2347bc9aa5b2070055d

Please also share your video screenshot so i can know understand it clearly. Thank you!

**Comment by xwr870312** [comment]
Thanks for your reply.
I already had the same paypal setting like the screenshot you sent to me.
At the moment, there're 2 issues for me: 

1. Stuck on the payment page when submit form using Stripe, I got this error on reactotron(see screenshot below)
<img width="646" alt="screen shot 2017-07-30 at 10 26 47 am" src="https://user-images.githubusercontent.com/17407114/28750109-a0ea02f8-7511-11e7-970f-297bd14efe34.png">
## Just wondering what is the folder 'StripeServerNode' used for? Do i need to upload this to server?
And what should i put in serverURL in constants.js for stripe(see screenshot below)?
<img width="492" alt="screen shot 2017-07-30 at 10 31 10 am" src="https://user-images.githubusercontent.com/17407114/28750128-615af3d0-7512-11e7-95ea-47e50cc7fc14.png">

2. Paypal just kept kicking me out the app when i choose it as my payment method.

BTW, do you have skype?

Thanks,

Ryan

**Comment by xwr870312** [comment]
@alien3d just wondering how did you setup the Stripe and Paypal, what do i need to do besides constants.js 
Very appreciated. I'm new to app development.

Ryan

**Comment by alien3d** [comment]
@xwr870312  later i try to document all API in here ya.. in pdf.. I do always document thing when i do code.Not remember all language as i work till now.
 
** not inspireui guys

**Comment by xwr870312** [comment]
Awesome! Thanks for doing that. @alien3d 
That would be fantastic if it includes Stripe and Paypal setup. 

Ryan

**Comment by xwr870312** [comment]
Hi @alien3d, just wondering do you have whatsapp or wechat so i can contact you?

Thanks,

Ryan

**Comment by alien3d** [comment]
Hi got whatsapp @xwr870312  but i'm not sure i can post here.. mostly at https://discordapp.com .. as same alien3d ..

**Comment by xwr870312** [comment]
@alien3d I sent you an email last week. Could you please check it?

Ryan

**Comment by alien3d** [comment]
e-mail ?  which e-mail you send ?  i now only official using admin@idcms.xyz.. hafizanil@gmail.com is rarely i used nowdays.

**Comment by xwr870312** [comment]
@inspireui Could you please write a help document for Stripe API? It would be very helpful to setup with a document from developer.

Ryan

**Comment by inspireui** [comment]
Hi guys, thank you so much for your supporting so far, especially from @alien3d documents, please have a look to this guide https://www.youtube.com/watch?v=6hNz43oTyUA&list=PLcF-HiQy-jOKIwJy97nNmiJGDpgZ0ckaP&index=3 for the payment stuff.

You need to run the StripeServerNode as the node server if you need to process payment with Stripe (required installing on hosting when you release the app), this server is used to store the private key and handle the rest payment when getting the token from the app.

Stripe integration is using tipsi/tipsi-stripe but this is not better than the web solution when showing the stripe form inside the webview, we have tried the webview solution but Stripe is having a bug with the agent when using React Native webview, that cause not good UX as when checking the same on mobile device. We are following this issue when upgrade the stripe payment with webview when they resolved the problem. 

Let me know if you need any payment support.

**Comment by xwr870312** [comment]
@inspireui Thanks for your reply. I will give it a go based on your video today. I pretty much know how to set it up now:) BTW, just wondering how can i install StripeServerNode on server? Using SSH?

Ryan

**Comment by inspireui** [comment]
Yes, ssh would be good or some hosting provide the terminal inside the browser.

**Comment by xwr870312** [comment]
Hi@inspireui @alien3d ,

Yesterday i successfully set up Stripe on IOS, and it ran smoothly. I'm looking for the Node hosting at the moment. If digital ocean is cost effective and easy to setup, i will definitely use it:) 
BTW, i couldn't get receipt email/notification email when pay using app. Is this a bug or i didnt setup correctly?

Ryan

**Comment by alien3d** [comment]
@xwr870312 
I'm use  namecheap, it can ssh and their support pretty good .. I before using digital ocean.. Till one time they moved my portlet and  cannot be access for few days..i'm quite using it.. Eventhou they said sorry,i'm kinda scare. Setting manually e-mail on digital ocean kinda a lot of hassle.  I'm not sure either woo commerce create a trigger upon receiving an invoice.

**Comment by inspireui** [comment]
Hi, Linode and Lightsail from amazon is also good in the list. 

Hi @xwr870312  could you check the SMTP is set up all correctly ? It could be an issue if only the email from payment not sending.

**Comment by xwr870312** [comment]
Hi @inspireui , i have setup nodejs on Heroku which is pretty good as well. 
Now Stripe and Paypal works fine like charm now! 
Just wondering are you gonna update the facebook login bug in #28? I have the same issue as well.

Ryan

**Comment by inspireui** [comment]
Great job Ryan, please help to give that charm to our rating comment, appreciated for your help.

Regarding to #28, please try to use the same component from Expo and copy to pro version will be fix the issues. We will also update this bug on next release. Thank you!
