### ISSUE TITLE
login page , signup page and checkout page 

### ISSUE THREAD

**Issue by xa9** [inspireui/mstore#28]
hi 

if you enter your id and pass app only loading nothing change and you can click the slide your id already login for example the screenshot 👍 
![screen shot 2017-07-24 at 6 02 39 pm](https://user-images.githubusercontent.com/29809274/28607019-92d93bfc-71e2-11e7-9bbf-5ad086816f37.png)
![screen shot 2017-07-24 at 6 03 01 pm](https://user-images.githubusercontent.com/29809274/28607020-932b3e16-71e2-11e7-8209-98b06b71b27f.png)

checkout page 👎 
check the screen shot 
![screen shot 2017-07-24 at 6 03 17 pm](https://user-images.githubusercontent.com/29809274/28607046-af3b95ce-71e2-11e7-8a7a-3cfbb88082ab.png)

last question can i change navigation bar weight its very small

**Comment by antoine15** [comment]
Hi,
Same problem for me for the login page.

**Comment by inspireui** [comment]
Thank you, looks like it an issue on pro version as we remember to fix it, we will update this UI on next version :)

**Comment by xa9** [comment]
When the next update is completed?

Can you give me a date

**Comment by inspireui** [comment]
it's around next week as we are working on other variants issues and checking the coupon features. In the meantime you can reused the same components from the expo version, this could be a quick fix. Thank you

**Comment by xa9** [comment]
Ok thanks for feedback 

We Use the expo that quick fix .

**Comment by jeemok** [comment]
Hi @inspireui , is there any updates on this issue? :)

**Comment by xa9** [comment]
Hi @inspireui , When the next update is completed?

**Comment by inspireui** [comment]
Hi, we are working on this issue, we have plan to upgrade new bug fix on around this wee, sorry for the delay as we have some issue with other release projects.

**Comment by GoldAndLink** [comment]
@xa9 and @antoine15 did you try to uncomment this part in the mstore-pro ? 

> [src/containers/login/index.js l52]
`componentWillReceiveProps(props) {
    const {user} = props.user;
    if (user) {
      this.props.onViewHomeScreen();
    }
  }`
It works for me

**Comment by inspireui** [comment]
Hi @xa9 could you try with new v3.3 to see if you are happy with the fix. Thank you!

**Comment by inspireui** [comment]
Confirmed this
