### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by faysal515** [inspireui/mstore#3]
![image](https://user-images.githubusercontent.com/10289348/27744541-a8a6b6f4-5de1-11e7-905f-7007542df0c1.png)

**Comment by inspireui** [comment]
Hi please try to copy this folder - https://www.dropbox.com/s/2uyc2210nvkltpf/android.zip?dl=0 and override to the android folder in your project to see if it can be fix, and make sure your Android SDK, Android Support Repository, Google Play service, Google Repository,  Intel x86... is update to latest version - https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md

**Comment by faysal515** [comment]
after replacing file, i'm getting this error
![image](https://user-images.githubusercontent.com/10289348/27759303-647d9b28-5e4f-11e7-8a36-5a183e6c5547.png)

**Comment by inspireui** [comment]
Hi, we are having the missing package on Envato as they are update old package, we have uploaded it again and you will have new v3.1 in 1-2 days, if you can wait please email to our support email with your purchase code to get it soon. Thank you!

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 is more stable and good performance now. Feel free to reopen again if you still have this issue. Thank you for your feedback
