### ISSUE TITLE
cannot get data

### ISSUE THREAD

**Issue by MRrnumber** [inspireui/mstore#30]
I am getting this error,
Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

**Comment by alien3d** [comment]
It's a mess error from updating 15.5 react to react 16. You have to manually changed the npm and never to update .. it's freakin annoying  for dependency management .. Blaim facebook people for changing.

**Comment by MRrnumber** [comment]
I did not update, the expo apps got updated by itself,

**Comment by alien3d** [comment]
Yes, i dam annoy with it..

**Comment by inspireui** [comment]
Hi you can ignore it that warning message, try to use the disableYellowBox or the config ReactotrongConfig.js in the app. We are not suggest to upgrade the current React & React Native version from the app as it will cause some incompatible library issues, we will follow React Native team and upgrade the versions when there are any major upgrade. 

Feel free to reopen this issue if you can still have the problem. Thank you!
