### ISSUE TITLE
Cannot customize to my store.

### ISSUE THREAD

**Issue by cheekuji** [inspireui/mstore#31]
I have modified the app config files but still the app is not connecting to my store. It does give me consumer key is invalid message. Can you tell me if there is another place to changed URL. I already changed it : Wordpress API from the app config file: src/common/Constants.js  but still I see your store (demo) and products. Please help

**Comment by cheekuji** [comment]
I am a paid customer so this error is for pro edition.

**Comment by alien3d** [comment]
you need to revoke it... and create a new one. 
https://github.com/inspireui/mstore/issues/26 
** i'm not inspireui

**Comment by inspireui** [comment]
Hi, it could cause some some reason, please check if it's one of your case:
- The Rest API Endpoints can be reachable - your-site/wp-json/wc/v2, example: mstore/wp-json/wc/v2
- Your local Wordpress website your be virual-host or it's release to the domain name (it's not run on localhost as your app could not connect)
- The Permalink Settings from Wordpress should be Post Name.

Thank you
