### ISSUE TITLE
Request features: Please add auction feature and inbuilt webwiew

### ISSUE THREAD

**Issue by nasirdavinci** [inspireui/mstore#32]
I think many people will find it great. Webview is most important feature. You can add auction later but with webview we can add it manually many things in the app.

**Comment by alien3d** [comment]
I prefer they settle existing bugs rather then publishing new future.. And web view just alternative and shouldn't be primary thing..

**Comment by inspireui** [comment]
Noted, please move to https://inspireui.ticksy.com/ - Thank you !
