### ISSUE TITLE
Notification / Receipt Email

### ISSUE THREAD

**Issue by xwr870312** [inspireui/mstore#33]
For next update, could you please have a look into notification / receipt email after placing the order using Stripe or Paypal?

Thanks,

Ryan

**Comment by inspireui** [comment]
Hi Ryan, could you check if your SMTP is all set up ok with the Wordpress, does it send email notification right after the registration or ordering the product ?

**Comment by xwr870312** [comment]
Hi @inspireui ,

I fixed it. My smtp was using the wrong settings.
Thanks for your help.

Kind regards,

Ryan

**Comment by inspireui** [comment]
Great Ryan, You are welcome!
