### ISSUE TITLE
demo WP site "Invalid timestamp"

### ISSUE THREAD

**Issue by basechain** [inspireui/mstore#34]
images  below:

[http://wx1.sinaimg.cn/large/005HEdDOgy1fic6hgr2m8j30hs0vatba.jpg](http://wx1.sinaimg.cn/large/005HEdDOgy1fic6hgr2m8j30hs0vatba.jpg)
[http://wx3.sinaimg.cn/large/005HEdDOgy1fic6hgj9cdj30hk0vkq4b.jpg](http://wx3.sinaimg.cn/large/005HEdDOgy1fic6hgj9cdj30hk0vkq4b.jpg)

[http://wx2.sinaimg.cn/large/005HEdDOgy1fic6hh2pffj30ke10mzom.jpg](http://wx2.sinaimg.cn/large/005HEdDOgy1fic6hh2pffj30ke10mzom.jpg)

**Comment by inspireui** [comment]
Hi, this is cause by the wrong file config, could you attache your site config or send to our support email: suppor@inspireui.com. Thank you

**Comment by inspireui** [comment]
Please download the latest version v3.3.1 which is more stable and cover this issue. Thank you!
