### ISSUE TITLE
Trouble with compiling the builds

### ISSUE THREAD

**Issue by Taimoormk** [inspireui/mstore#35]
I have added the project file and installed all the required modules by running {npm install} command, but when I am running {react-native run-ios} I am getting this error thrown;

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/taimoorkhan/mstore-pro/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKGraphRequestManager.o RCTFBSDK/core/RCTFBSDKGraphRequestManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by emiryayla** [comment]
I fixed that like this = download facebook SDK and copy your ˜/Documents folder and Rename  that folder FacebookSDK

**Comment by Taimoormk** [comment]
Thank you @emiryayla your suggestion worked, cheers.
