### ISSUE TITLE
error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by azamkth** [inspireui/mstore#36]
ld: warning: directory not found for option '-L/Users/xyz/Library/Developer/Xcode/DerivedData/beostore-etbeaamwtiqobffjljdxwchzcgew/Build/Products/Debug-iphonesimulator/Stripe'
ld: library not found for -lStripe

![untitled22222](https://user-images.githubusercontent.com/5824027/29113327-ffa0c548-7cf0-11e7-90f3-498ef858a004.png)

**Comment by inspireui** [comment]
Can you run this cmd to check if the issue is fixed: react-native link
