### ISSUE TITLE
Theme missing?

### ISSUE THREAD

**Issue by Bits101** [inspireui/mstore#37]
The theme in the app is missing then the theme in the screenshots. Can you tell me where can I find the screenshot theme in your code.

The one I have, has the options underneath but the screenshot ones actually have them in tabs in the frontend. Also where can I find the homepage/category page where all the main categories are in the app.

i.e the first picture in your demo screenshots “Features & Screenshots” the girl with the yellow dress. (I am talking about this page)

I will add screenshots once you fix the broken screenshots on your page 
https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642

**Comment by inspireui** [comment]
Hi, we have updated the screenshot

**Comment by Bits101** [comment]
Hi,

I am not getting the below theme structure when I go to the product page and I am unable to see the homepage where all the categories are. Is this theme missing or is it a setting?


![687474703a2f2f6d73746f72652e696f2f77702d636f6e74656e742f75706c6f6164732f323031372f30362f62616e6e65722e706e67](https://user-images.githubusercontent.com/17542308/29260174-dd63abba-80d0-11e7-860d-5578735d8efc.png)

**Comment by inspireui** [comment]
Hi, it could be your setting issues, could you please also share your screenshot ?
