### ISSUE TITLE
Build fails in IOS 

### ISSUE THREAD

**Issue by jlsupport** [inspireui/mstore#38]
Hi,

i´m getting this:

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/lars/Desktop/mstore.3.2.1/mstore-pro/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSCardField.o TPSStripe/TPSCardField.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

when i check in xcode "TPSStripe.xcodeproj" it says **"..../mstore-pro/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:9:9: 'React/UIView+React.h' file not found"**

**Comment by inspireui** [comment]
Could you try to remove node_module and try these command line:
```
yarn install
react-native link 
yarn start --reset-cache
react-native run-ios
```

**Comment by jlsupport** [comment]
react-native link gives below error:

rnpm-install info Linking react-native-fbsdk ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

But still not work, same error

**Comment by inspireui** [comment]
Hi @jlsupport this issue from latest version of react-native-fbsdk, please try to remove and link it with v0.6.0:

```
yarn remove react-native-fbsdk
yarn add react-native-fbsdk@0.6.0
```

**Comment by jlsupport** [comment]
still getting this error:
The following build commands failed:

	CompileC /Documents/mstore.3.2.1/mstore-pro/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSCardField.o TPSStripe/TPSCardField.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by minhcasi** [comment]
Hi, could you try to have a look to this document from stripe lib to reinstall this libary - https://github.com/tipsi/tipsi-stripe

Or you can try to run: react-native link tipsi-stripe

**Comment by inspireui** [comment]
Hi, could you download the latest version v3.3.1 to see if it is fixed your issue? we are happy to remote support if you are still trouble. Thank you!
