### ISSUE TITLE
Failed in Facebook login 

### ISSUE THREAD

**Issue by jeemok** [inspireui/mstore#39]
Hi @inspireui,

I'm setting up mstore on `mstore-expo` version, everything was good and I was trying to update the Facebook login app to my facebook app.

So I changed the `appFacebookId ` from `common/Constants.js` and tried to login, but got the error below:

`You are not logged in: You are not logged in:. please login and try again`

Is there any other steps/config I should setup?

**Comment by inspireui** [comment]
Hi, could check to update the Facebook config base on guide from - https://mstore.gitbooks.io/mstore-manual/content/chapter4.html

You need to change the Info.plist as well

**Comment by jeemok** [comment]
Sorry if I didn't get it right, but isn't that guide was for `mstore-pro` version ?

**Comment by minhcasi** [comment]
Oh sorry, it's for pro version, please check this document to setting your facebook app first - https://docs.expo.io/versions/latest/sdk/facebook.html, make sure the bundle ID and key hash is the same. Let me know your checking then.

**Comment by inspireui** [comment]
Hi @jeemok, i'm losing this ticket as it looks resolved, fell free to reopen if you still have trouble with it. Thank you very much for your support!

**Comment by jeemok** [comment]
hi @inspireui @minhcasi,

I'm quite fond with building the app with Expo, may I ask if there is anyway I can use my own Facebook page for Expo version FB login?

Many thanks,
Mok

**Comment by inspireui** [comment]
Yes sure, config the facebook login on Expo quite easy to update the config.js/constants.js file, please have a look more to this doc - https://docs.expo.io/versions/latest/sdk/facebook.html#registering-your-app-with-facebook

**Comment by jeemok** [comment]
Thanks for the ref, I was able to set up correctly in Expo version! :)

However, when user first time login through Facebook, it will require user to sign up in order to proceed; and when the second time user login again through Facebook login, it still prompt out Sign up page for user. Do you know how I could fix it?

Steps to reproduce:
1. Sign in using Facebook ( prompt up sign up page )
2. Sign out
3. Sign in again using Facebook ( still prompt up Sign Up page )

Thanks!
Mok

**Comment by jeemok** [comment]
Turns out it was because the Key Hashes doesn't match with the one I set in the Facebook developer page. Everything is good now!

Thanks!
Mok
