### ISSUE TITLE
Error when run Expo

### ISSUE THREAD

**Issue by wphjaelpen** [inspireui/mstore#4]
Why does I always get this error, when I run the expo app?
See screenshot from my iPhone: https://cl.ly/3q2w421U0K3X

**Comment by inspireui** [comment]
Hi, it could be cause by empty product attribute config, please try to add some product attribute like this - https://gyazo.com/4943a80f0c995a41325d7a862ae49df9, we will check this issue to cover for the site not using attribute.

**Comment by wphjaelpen** [comment]
Yeah, I think that fixed the problem :) thanks 👍
