### ISSUE TITLE
App Build is successful but getting error kindly check the attachment. 

### ISSUE THREAD

**Issue by chandshah** [inspireui/mstore#40]
![app error](https://user-images.githubusercontent.com/31177480/29493005-303d1a28-85aa-11e7-94ff-4cc61bedac99.png)

**Comment by inspireui** [comment]
Hi can we check if it is ok if you run the testing project via:
`
react-native init ExampleProject
cd ExampleProject
react-native run-android
`

**Comment by wmirchi** [comment]
Hello, 

I'm getting following error

E:\App Devlopment\mStore\mstore\mstore-pro>yarn
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 5.59s.

E:\App Devlopment\mStore\mstore\mstore-pro>react-native init ExampleProject
Scanning 605 folders for symlinks in E:\App Devlopment\mStore\mstore\mstore-pro\node_modules (193ms)
Looks like React Native project already exists in the current
folder. Run this command from a different folder or remove node_modules/react-native

E:\App Devlopment\mStore\mstore\mstore-pro>cd ExampleProject
The system cannot find the path specified.

**Comment by wmirchi** [comment]
Hello,

after renaming the old react-native i can able to do this 
Now I'm getting following error 

======

E:\App Devlopment\mStore\mstore\mstore-pro\ExampleProject>react-native run-android
Scanning 474 folders for symlinks in E:\App Devlopment\mStore\mstore\mstore-pro\ExampleProject\node_modules (76ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

E:\App Devlopment\mStore\mstore\mstore-pro\ExampleProject>

**Comment by minhcasi** [comment]
Hi, please test the ExampleProject from outside the mstore project as it will conflict with the library.

The purpose of checking example project is just make sure your have set up all requirement for React Native framework, if you have check it all good and can run on your simulator then you can go to Mstore project and run the same steps.

Thank you!
