### ISSUE TITLE
undefined is not an obect(evaliating 'user.shipping.address_1')

### ISSUE THREAD

**Issue by cheekuji** [inspireui/mstore#43]
I cannot launch the app anymore I get this red screen with the above message. Please help. This is for pro version.

**Comment by inspireui** [comment]
Hi, could you share your WooCommerce URL and consumse key so we can help to have a look (you can send to our support email support@inspireui.com)

**Comment by cheekuji** [comment]
The default store url:    
url: 'http://mstore.io',
    consumerKey: 'ck_b7594bc4391db4b56c635fe6da1072a53ca4535a',
    consumerSecret: 'cs_980b9edb120e15bd2a8b668cacc734f7eca0ba40',

**Comment by inspireui** [comment]
Hi, we update this issue and bug and will fix on next couple of days. Thank you!

**Comment by inspireui** [comment]
i'm closing ticket issue as it is fixed on v3.3, kindly reopen it you still have an issue. Thank you!
