### ISSUE TITLE
draw over other apps

### ISSUE THREAD

**Issue by prostata84** [inspireui/mstore#46]
When I start my app (generated by Android Studio), the "draw over other apps" comes out. How do I delete this alert? What should I change in my project?

**Comment by inspireui** [comment]
Hi, you can try to turn on the option then restart the app again, this is normal behavior on Android OS. Thank you

**Comment by prostata84** [comment]
Thanks, I know it's a normal behavior. I wanted to know if you can delete this behavior by modifying the application code. I would like this behavior never to happen. Thanks again.

**Comment by inspireui** [comment]
Hi, once you release the app without the debug mode, it will work as normal

**Comment by inspireui** [comment]
i'm closing ticket, kindly reopen it you still have an issue. Thank you!
