### ISSUE TITLE
"Contact us" page

### ISSUE THREAD

**Issue by prostata84** [inspireui/mstore#47]
How do you edit the "Contact us" page in the android app? I use Android Studio. Thank you.

**Comment by inspireui** [comment]
Hi, you can edit it direct from the Wordpress page, from the constants.js file there is the config the contact page which is used to map to the post id from wordpress.

**Comment by jeemok** [comment]
@prostata84 after you publish a new page in WooCommerce, you may get the page id from the URL, eg:
yourwebsite.com/wp-admin/post.php?post=**476**&action=edit

Then you can use it to update the `contact_id `in /constants.js

![screenshot_3](https://user-images.githubusercontent.com/26216852/29802713-b083ad40-8ca9-11e7-8a74-c5e894200e39.png)

**Comment by inspireui** [comment]
i'm closing ticket issue, kindly reopen it you still have an issue. Thank you!
