### ISSUE TITLE
Problem with attributes on custom woocommerce installation

### ISSUE THREAD

**Issue by deenoize** [inspireui/mstore#48]
Hey, guys! I have already working website [taboo.world](https://taboo.world/shop) and there are a couple of variants as well as attributes of each product. After pointing Mstore to it Build is successful and everything starts but after welcome page I get 
`null is not an object (evaluating variation.attributes)`

How can I handle this?

**Comment by inspireui** [comment]
Hi, thank you for your feedback, we are checking the solution to handle the variant more flexible, this bug fix will be updated on next version (around 1-2 week)

**Comment by deenoize** [comment]
Hey, guys! Any luck with this one? @inspireui

**Comment by inspireui** [comment]
Hi, this is really a complexity function and it took us longer time than expect but i've already resolve it and will be update the new version on this week. Thank you for your patient !

**Comment by deenoize** [comment]
Appreciate it! Thanks!

**Comment by inspireui** [comment]
i'm closing ticket issue as it is fixed on v3.3, kindly reopen it you still have an issue. Thank you!

**Comment by deenoize** [comment]
Thanks guys! Will check it in a few days
