### ISSUE TITLE
Couldn't receive Phone & Address information in WooCommerce

### ISSUE THREAD

**Issue by jeemok** [inspireui/mstore#49]
Hi,

I am building the App using Expo version and tested an order with real payment using PayPal. Everything was working good, except that in the WooCommerce, the Phone and Address field failed to capture the information I wrote from the app. Is it a known issue? 

Other features were great to use!

Thanks,
Mok

**Comment by inspireui** [comment]
This could release to this issue - #43, i'm updating it as bug

**Comment by masoudkhademi** [comment]
hi , this is my problem too , every thing works ok , but the phone number and address failed to capture  and actually woocommerce can't capture the information that we enter in the "yourdeliveryinfo" field.

**Comment by jeemok** [comment]
@masoudkhademi here's what I did to add the information to WooCommerce. It's just a quick fix for now and we should update it when inspireui updates the file. You may refer to my solution if you need a quick fix urgently:

1.	At (/src/containers/Cart/Delivery/index.js) line 47
Change `this.props.onNext()` to `this.props.onNext(this.customerInfo)`

2.	At (/src/containers/Cart/index.js)
Create a new method
`
deliveryNext = deliveryUserInfo => {
    This.props.user.user.billing = deliveryUserInfo;
    This.props.user.user.shipping = deliveryUserInfo;
    // check validate before moving next
    ... same as onNext function
}
`
Then update below's code
`
<Delivery key="delivery" onNext={this.deliveryNext} onPrevious={this.onPrevious}/>
`

Still, I'd not recommend this way of directly modifying `this.props`. But if you want something that works for now, this might helps before the next release.

**Comment by abhishekdhiman095** [comment]
is some step missing,
beacause its showing errors on changing it.

**Comment by jeemok** [comment]
I just reroute a new handling for delivery info, what are the errors shown on your side?

**Comment by abhishekdhiman095** [comment]
Actually i had mstore pro version,now working fine
 Thank you for replying

**Comment by inspireui** [comment]
i'm closing ticket issue as it is fixed on v3.3, kindly reopen it you still have an issue. Thank you!
