### ISSUE TITLE
add new language 

### ISSUE THREAD

**Issue by xa9** [inspireui/mstore#5]
in your https://mstore.gitbooks.io/mstore-manual/content/pro-version/multi-languages.html

the code is different with a new update 

![screen shot 2017-07-01 at 7 07 50 am](https://user-images.githubusercontent.com/29809274/27759042-0f56f99a-5e2d-11e7-9275-6be59cfa3d3e.png)

how to edit it ?

**Comment by inspireui** [comment]
Hi, sorry for the confuse, we have updated new v3.1 version with new Language update so it will match with the document, it will be available in 1-2 days.

**Comment by xa9** [comment]
Thanks
