### ISSUE TITLE
product apereance

### ISSUE THREAD

**Issue by masoudkhademi** [inspireui/mstore#51]
when i use sale price for products in woocommerce , the app just shows one price and the regular price goes out of screen .you can see the screen shot in the this link :
http://sofs.ir/wp-content/uploads/2017/09/Screenshot_2017-09-04-20-39-52.png

**Comment by inspireui** [comment]
I see, it because your language is to long and also the number, please try to format that component to enter new line for update the font smaller. Thank you!
