### ISSUE TITLE
icons are hidden when i reopen the app after some hours

### ISSUE THREAD

**Issue by masoudkhademi** [inspireui/mstore#53]
i have installed the app many times ,but after some hours that i reopen the app , icons of tab bar are hidden . here is the screenshot:
http://sofs.ir/wp-content/uploads/2017/09/photo_2017-09-08_11-58-06.jpg

**Comment by inspireui** [comment]
Hi Could you let me know which Android version that you are using to test, please make sure your Android SDK should be the same with this installing guide - https://gyazo.com/5cc342b4111f066b3ba19b594c644e95

**Comment by inspireui** [comment]
Hi @masoudkhademi could you check to see if this issue is still happening on latest build v3.3.1. Thank you!
