### ISSUE TITLE
back icon doesn't work properly... while every thing is ok at demo app

### ISSUE THREAD

**Issue by masoudkhademi** [inspireui/mstore#54]
when i am in the product page , and touch back icon, it goes back two step .. when i touch back , it must go to its category screen such as demo app , but now it goes to home screen ... while in the demo app there is none of this problems ... is it possible for me to have demo app's theme?

**Comment by inspireui** [comment]
Hi, it is the same code base with the demo app, could you let me know which the version you are using to test, pro or Expo version ? Thank you!

**Comment by inspireui** [comment]
i'm closing ticket issue as it is fixed on v3.3, kindly reopen it you still have an issue. Thank you!
