### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by f0rtun3** [inspireui/mstore#55]
I recently bought the Mstore template,
I cant seem to get it running on my expo, here are the versions of tools I'm using.
React Native 0.46.1
Expo version 20.0.0
Node.js v6.11.2

Username: f0rtun3
purchase code: b1582a68-9ff7-445d-9de0-4add50221270

**Comment by inspireui** [comment]
i've released new v3.3 which is support latest Expo version update, please download and test it again. Thank you!
