### ISSUE TITLE
¿Why products appear repeated in different categories?

### ISSUE THREAD

**Issue by mustymx** [inspireui/mstore#56]
¿Why products appear repeated? for example: in a category I only have one product in woocommerce, however in the app show product many times

**Comment by inspireui** [comment]
Hi could you help to send your constants config file to our support email: support@inspireui.com so that we can check the duplicate issue on category page, if it is a bug we will fix on next version. Thank you!

**Comment by inspireui** [comment]
Hi, confirmed that this issue will be fix on v3.3, this is already released and you will get the notify email to download soon. Thank you!
