### ISSUE TITLE
the images dons't show on the app

### ISSUE THREAD

**Issue by haysamelmasry** [inspireui/mstore#57]
hi 
i have 3 problems 

1 - the product images doesn't show on the app 
2- the checkout page on delivery section doesn't have enough info like the demo app on play store like country postcode etc..
3- the login page doesn't redirect after i login it just stay on the same page

**Comment by inspireui** [comment]
Hi please check the #1 by config "Product Display Sizes"- https://mstore.gitbooks.io/mstore-manual/content/chapter5.html

The issue 2-3 will be fixed on v3.3, you will get the notify to download the new version soon, we have already upload the package.

Thank you!

**Comment by inspireui** [comment]
Hi, i'm closing this issue as it is fixed on latest version v3.3.1. Thank you!
