### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by brainonline-ro** [inspireui/mstore#58]
I would like to convert the store www.shop.meatbox.ro into an iOS application, is WordPress with WooCommerce, is there an option to download through the AppStore? I am interested in extracting the products from the website and exporting them in the mobile application, with pictures, details and the ability to buy the products displayed on the shop.

I bought Envato’s BeoStore, please help me configure the little build, how do I import the products from the website and how to publish the app on AppStore?

‘RCTOneSignal.h’ file not found

‘React/RCTBundleURLProvider.h’ file not found

**Comment by brainonline-ro** [comment]
I will pay if you help me to configure.

**Comment by inspireui** [comment]
Hi, thank you for your purchased and comment on github, please send us your Skype ID to our support email support@inspireui.com for further discussion. Thank you!
