### ISSUE TITLE
Issues (or bugs) with Price and BuyNow Button

### ISSUE THREAD

**Issue by mustymx** [inspireui/mstore#59]
<a href="https://imgur.com/dZMoOgv"><img src="https://i.imgur.com/dZMoOgv.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/5vBp8vE"><img src="https://i.imgur.com/5vBp8vE.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/xYje0TC"><img src="https://i.imgur.com/xYje0TC.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/SKswZ5V"><img src="https://i.imgur.com/SKswZ5V.gif" title="source: imgur.com" /></a>

**Comment by inspireui** [comment]
Thank you for your detail screenshot, we will have a check and update the hotifx soon if it is an issues

**Comment by mustymx** [comment]
"Soon" is a very abstract time form, give me a date time, please.
I already paid for a product to help me save time and not start a project from scratch.
Please fix it real soon.

**Comment by inspireui** [comment]
Hi, it's around 1-2 days for the hotfix. Thank you!

**Comment by inspireui** [comment]
Hi, can we know your email to send the hotfix please?

**Comment by mustymx** [comment]
mustymx@hotmail.com
thanks!

**Comment by inspireui** [comment]
Confirmed this will be fixed on v3.3.1 which will notify in 1-2 days, if you can't wait please send your request download to our support email support@inspireui.com (with your purchased code). Thank you!

**Comment by inspireui** [comment]
Hi @mustymx could you check the latest package and happy to close this ticket ?

**Comment by mustymx** [comment]
Thank you, these issues have already been resolved.

**Comment by mrsof** [comment]
Thx for quick support. But I am still facing some issue Pls check these pastebin to see what I did and the error throwed.

https://pastebin.com/gkfTzU0N
https://pastebin.com/GrXj3LiT

Also, I do not find anymore the “android/local.properties” file in the new package. Should I create it ?

Thx

**Comment by mrsof** [comment]
I have found the solution
https://stackoverflow.com/a/42644364/1458189
Solved!
