### ISSUE TITLE
Issues in 3.1

### ISSUE THREAD

**Issue by enriqueguardia** [inspireui/mstore#6]
Hey guys. The app is looking great but here are some issues I found:

1. If you constantly scroll down in the home screen, the app freezes and exits to Android home screen.
2. All the orders placed show as amount 0.00 on the WooCommerce backend. Instead of the real amount placed by customer.
3. When you press on BUY NOW, it takes you to your cart but does NOT add the product to your cart.
4. The Facebook login works great, but when you logout and then log back in, it shows this error: https://ibb.co/gvx1Hv
5. When you add or rest a product from your cart, it takes you back to that product's info page. Here is gif showing this error: https://ibb.co/gvx1Hv
6. The My Orders screen is blank. It doesn't show anything.

And here is one suggestion:

1. In V2 we had a Settings area within the Menu, where you could see the company info and also change the language. Through coding, you could also add custom modal boxes. It would be great if this could return because it was a quick way for customers to see extra info.

Hope to see some fixes very soon. Regards.

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 are fixed all these issues. Please help to open new ticket if there are still issues. Thank you so much for your feedback
