### ISSUE TITLE
api response 404,401

### ISSUE THREAD

**Issue by emiryayla** [inspireui/mstore#60]
http://greentous.com/wp-json/wc/v2/products/1/variations?oauth_consumer_key=ck_3444b9c889b68ad0b1b0622445d4e8f616637d4b&oauth_nonce=KFbh62fW9jKhmLo57iiPR00FUKoSI6RE&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1506325763&oauth_version=1.0&per_page=100&page=1&oauth_signature=z6EnRt08sobdoZn%2BTpY6ot814rMuOlxcxZFK9RaOEaY%3D

Status Code
401
Method
GET
Duration (ms)
663.9139720015228
-------------------------------------------

http://greentous.com/wp-json/wc/v2/products?oauth_consumer_key=ck_3444b9c889b68ad0b1b0622445d4e8f616637d4b&oauth_nonce=wXFhPZn8ihzUjMeZfl957jG94UX0PJDD&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1506325690&oauth_version=1.0&per_page=10&page=1&purchasable=true&category=21&oauth_signature=GHXog93llAFYkgJn1CMY3m0DJ6SXAMdEZxOtF09id%2F4%3D

code:woocommerce_rest_cannot_view
message:Sorry, you cannot list resources.
▶data:{}
status:401

**Comment by inspireui** [comment]
can you check the setting/permalink is Post name? like this screenshot - https://gyazo.com/4c82dcf2b5236ca986d9abc40204b794

**Comment by emiryayla** [comment]
yes it is. same selection I got but nothing...!

**Comment by inspireui** [comment]
Hi, looks like your Rest API is not enable from the WooCommerce setting so that you could not reach to the endpoint - http://greentous.com/wp-json/wc/v2

it should be returned the data like this - http://mstore.io/wp-json/wc/v2
