### ISSUE TITLE
Can't build ios version

### ISSUE THREAD

**Issue by karim-aly** [inspireui/mstore#61]
Error Log:

>** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c

(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSCardFieldManager.o TPSStripe/TPSCardFieldManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

> Detailed Error Log Above Build Log
In file included from /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:10:
In file included from /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:10:
../../../ios/Pods/Headers/Public/Stripe/Stripe.h:1:1: error: expected identifier or '('
../../../Stripe/Stripe/PublicHeaders/Stripe.h
^
In file included from /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:10:
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:15:1: error: unexpected '@' in program
@property (nonatomic, strong) UIFont *font;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:16:1: error: unexpected '@' in program
@property(nonatomic, strong) UIColor *textColor;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:17:1: error: unexpected '@' in program
@property(nonatomic, strong) UIColor *textErrorColor;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:18:1: error: unexpected '@' in program
@property(nonatomic, strong) UIColor *placeholderColor;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:19:1: error: unexpected '@' in program
@property(nonatomic, copy) NSString *numberPlaceholder;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:20:1: error: unexpected '@' in program
@property(nonatomic, copy) NSString *expirationPlaceholder;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:21:1: error: unexpected '@' in program
@property(nonatomic, copy) NSString *cvcPlaceholder;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:22:1: error: unexpected '@' in program
@property(nonatomic, strong) UIColor *cursorColor;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:23:1: error: unexpected '@' in program
@property(nonatomic, strong) UIColor *borderColor;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:24:1: error: unexpected '@' in program
@property(nonatomic, assign) CGFloat borderWidth;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:25:1: error: unexpected '@' in program
@property(nonatomic, assign) CGFloat cornerRadius;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:26:24: error: expected a type
- (void)setCardParams:(STPCardParams *)cardParams;
                       ^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:26:1: error: missing context for method declaration
- (void)setCardParams:(STPCardParams *)cardParams;
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:28:1: error: expected method body
@end
^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:30:46: error: expected a type
RCT_CUSTOM_VIEW_PROPERTY(fontSize, NSNumber, TPSCardField)
                                             ^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:30:46: error: expected a type
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:34:57: error: unknown type name 'TPSCardField'
RCT_CUSTOM_VIEW_PROPERTY(fontWeight, NSString, __unused TPSCardField)
                                                        ^
/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardFieldManager.m:34:57: error: unknown type name 'TPSCardField'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

CompileC /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSStripeManager.o TPSStripe/TPSStripeManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=10.0 -g -Wno-sign-conversion -Winfinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/TPSStripe-generated-files.hmap -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/TPSStripe-own-target-headers.hmap -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/TPSStripe-all-target-headers.hmap -iquote /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/TPSStripe-project-headers.hmap -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator/include -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/../../../React -I../../react-native/React -I../../react-native/React/Base -I../../react-native/React/CxxBridge -I../../react-native/React/CxxModule -I../../react-native/React/CxxUtils -I../../react-native/React/DevSupport -I../../react-native/React/Executors -I../../react-native/React/Modules -I../../react-native/React/Profiler -I../../react-native/React/Views -I../../../ios/Pods/Headers/Public -I../../../ios/Pods/Headers/Public/Stripe -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/DerivedSources/x86_64 -I/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/DerivedSources -F/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator -F/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator -F/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator/include -F/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator/include/yoga -F/Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Products/Debug-iphonesimulator/Stripe -MMD -MT dependencies -MF /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSStripeManager.d --serialize-diagnostics /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSStripeManager.dia -c /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/node_modules/tipsi-stripe/ios/TPSStripe/TPSStripeManager.m -o /Users/karimaly/Workspace/ReactNativeWorkspace/mstore-pro-3.2/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSStripeManager.o

**Comment by inspireui** [comment]
Hi, could you try this scrip to clean the cache  - https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9

Then try to run this cmd: react-native link

And let us know your checking. Thank you!

**Comment by karim-aly** [comment]
Same Error 
Output from react-native link:

> Scanning 656 folders for symlinks in /Users/karimaly/Workspace/ReactNativeWorkspace/kamkilo/node_modules (9ms)
rnpm-install info Android module react-native-admob is already linked 
rnpm-install info iOS module react-native-admob is already linked 
rnpm-install info Android module react-native-fbsdk is already linked 
rnpm-install info iOS module react-native-fbsdk is already linked 
rnpm-install info Android module react-native-linear-gradient is already linked 
rnpm-install info iOS module react-native-linear-gradient is already linked 
rnpm-install info Android module react-native-localization is already linked 
rnpm-install info iOS module react-native-localization is already linked 
rnpm-install info Android module react-native-onesignal is already linked 
rnpm-install info iOS module react-native-onesignal is already linked 
rnpm-install info Android module react-native-restart is already linked 
rnpm-install info iOS module react-native-restart is already linked 
rnpm-install info Android module react-native-vector-icons is already linked 
rnpm-install info iOS module react-native-vector-icons is already linked 
Preparing to link tipsi-stripe for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-install info Android module tipsi-stripe is already linked 
rnpm-install info iOS module tipsi-stripe is already linked 
Checking Podfile in iOS project /Users/karimaly/Workspace/ReactNativeWorkspace/kamkilo/ios/Podfile
Found an existing Podfile
Adding the following pod to Podfile
  pod 'Stripe', '~> 10.1.0'
Stripe pod is already added
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project

**Comment by lin-zy1229** [comment]
same issue of:

../../../ios/Pods/Headers/Public/Stripe/Stripe.h:1:1: error: expected identifier or '('
