### ISSUE TITLE
Question : update to new Rest API

### ISSUE THREAD

**Issue by mrsof** [inspireui/mstore#62]
When reading the docs [here](https://mstore.gitbooks.io/mstore-manual/content/pro-version/wordpress-installing.html) we have to add the old [JSON API REST](https://wordpress.org/plugins/json-api/) wich is not supported and not recommanded to install in WP 4.8+.

Do you plan to update mstore to use new fully integrated in Wordpress and WOOComerce REST API ?

**Comment by inspireui** [comment]
Hi, as we are still using this Json API User for authentication - https://wordpress.org/plugins/json-api-user/ so it's dependency to Json API Rest, we are waiting for the new WP API fully support then we can detach these plugins. Thank you!
