### ISSUE TITLE
WC does not receive address billing and phone

### ISSUE THREAD

**Issue by mustymx** [inspireui/mstore#63]
WC does not receive address billing and phone
<a href="https://imgur.com/v9uGRZz"><img src="https://i.imgur.com/v9uGRZz.png" title="source: imgur.com" /></a>

Once the order has been placed, the shopping cart must be emptied
<a href="https://imgur.com/zcWm2Gk"><img src="https://i.imgur.com/zcWm2Gk.jpg" title="source: imgur.com" /></a>

**Comment by inspireui** [comment]
Thank you for raise it, our technical guy is checking and have a hotfix in 1-2 days. Thank you!

**Comment by mustymx** [comment]
good afternoon, any news about the issues?

**Comment by inspireui** [comment]
fixed on v3.3.2
