### ISSUE TITLE
3.3, home view horizontal layout all items without image, price=$0.00

### ISSUE THREAD

**Issue by tstkenny** [inspireui/mstore#64]
It seems the app is unable to get anything from WC at all.

**Comment by inspireui** [comment]
Hi we will update the webconfig, in the meantime please check this document guide for the horizontal layout config - https://mstore.gitbooks.io/mstore-manual/chapter6.html

**Comment by inspireui** [comment]
Please check this readme to update the config for horizontal layout: https://github.com/inspireui/mstore/blob/master/Readme.md

This is also clarified from - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
