### ISSUE TITLE
3.3, home view card layout generates error in chrome debugger

### ISSUE THREAD

**Issue by tstkenny** [inspireui/mstore#65]
Setup: wordpress clone from your mstore repo.  Nothing updated inside.  Product image sizes matched in omni.js.  JSON API Settings plugin -> controllers all activated.  WC keys setup properly as in some views the app loads images & product details successfully.

1. Warning: `flexWrap: `wrap`` is not supported with the `VirtualizedList` components.Consider using `numColumns` with `FlatList` instead.

2. Warning: flattenChildren(...): Encountered two children with the same key, `27`. Child keys must be unique; when two children share a key, only the first child will be used.
    in RCTView (at View.js:133)
    in View (at ScrollView.js:668)
    in RCTScrollView (at ScrollView.js:744)
    in AndroidSwipeRefreshLayout (at RefreshControl.js:157)
    in RefreshControl (at index.js:117)
    in ScrollView (at VirtualizedList.js:318)
    in VirtualizedList (at FlatList.js:501)
    in FlatList (at index.js:108)
    in PostList (created by Connect(PostList))
    in Connect(PostList) (at index.js:18)
    in RCTView (at View.js:133)
    in View (at index.js:16)
    in Home (created by Connect(Home))
    in Connect(Home) (at HomeScreen.js:25)
    in HomeScreen (at SceneView.js:35)
    in SceneView (at CardStack.js:397)
    in RCTView (at View.js:133)
    in View (at CardStack.js:396)
    in RCTView (at View.js:133)
    in View (at CardStack.js:395)
    in RCTView (at View.js:133)
    in View (at AnimatedImplementation.js:1844)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:133)
    in View (at CardStack.js:368)
    in RCTView (at View.js:133)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:133)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at index.js:64)
    in screen (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:133)
    in View (at TabView.js:69)
    in RCTView (at View.js:133)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:133)
    in View (at AnimatedImplementation.js:1844)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:133)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at CardStack.js:397)
    in RCTView (at View.js:133)
    in View (at CardStack.js:396)
    in RCTView (at View.js:133)
    in View (at CardStack.js:395)
    in RCTView (at View.js:133)
    in View (at AnimatedImplementation.js:1844)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:133)
    in View (at CardStack.js:368)
    in RCTView (at View.js:133)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:133)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at Router.js:67)
    in RCTView (at View.js:133)
    in View (at Router.js:65)
    in RCTView (at View.js:133)
    in View (at AnimatedImplementation.js:1844)
    in AnimatedComponent (at index.js:538)
    in RCTView (at View.js:133)
    in View (at index.js:525)
    in Drawer (at MenuScale.js:24)
    in MenuScale (at Router.js:64)
    in Provider (at Router.js:63)
    in Router (at ReduxWrapper.js:124)
    in Provider (at ReduxWrapper.js:123)
    in ReduxWrapper (at renderApplication.js:35)
    in RCTView (at View.js:133)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:133)
    in View (at AppContainer.js:97)
    in AppContainer (at renderApplication.js:34)

**Comment by inspireui** [comment]
Thank you for your feedback, i've marked this ticket as bug for further update.

**Comment by inspireui** [comment]
fixed on v3.3.2
