### ISSUE TITLE
Pro Version bugs

### ISSUE THREAD

**Issue by kaledjeff** [inspireui/mstore#66]
Hello, 

I just purchased the template and I’m having trouble with pro version (The expo version seems to work except for one small bug).

Here are the messages after opening the project on Expo XDE:

Warning Warning: Not using the Expo fork of react-native. See https://docs.expo.io/. Warning Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\Admin\AppData\Local\Expo\schema-undefined.json: XDLError: Invalid JSON returned from API: SyntaxError: Unexpected token N in JSON at position 0. Response body: Not Found. Warning Warning: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 7.0.0, 8.0.0, 9.0.0

When I run project on the expo app on IOS, this message appears on Expo XDE:

error: bundling failed: “Cannot find entry file index.js in any of the roots: [\”C:\\\\Users\\\\Admin\\\\Documents\\\\mstore.3.3.1\\\\mstore-pro\”]”

and on the iphone, the error is this:

https://i.imgur.com/mG0jVtB.png?1
The bug on the expo version, tabbing on a product after using the searching function results in error.

Thanks

**Comment by inspireui** [comment]
Hi, for the mstore-pro version, you could not open the app via Expo XDE, it should be executed via command line: react-native run-ios

Or start from XCode or Android Studio

**Comment by kaledjeff** [comment]
After typing yarn start, I can't type anything.

It says "loading dependency graph, Done" and that is it.

I followed this documentation ( [https://mstore.gitbooks.io/mstore-manual/content/expo-version.html] ) which clearly says that you can use XDE but it didn't work.

I also tried the second method as the document suggested and the same errors appeared  as previously mentioned

https://imgur.com/a/6Hckk

**Comment by kaledjeff** [comment]
I don't have mac. So I can't use XCode.

**Comment by kaledjeff** [comment]
Any update on this?

**Comment by inspireui** [comment]
Hi, let me explain more about the step, for both versions you need to run: yarn install to setup the dependencies libraries, then
- Expo version (mstore-expo): open the Expo XDE (which is download from http://expo.io) or use exp like on your screenshot to run the app.
- Pro version(mstore-pro): you could not use exp cmd or Expo XDE on this version, instead use the react-native-cli to run the app by this command: react-native run-android (please make sure you have install Android SDK base on this guide - https://gyazo.com/42c89e8940494a7f8004c6f11a2ead28). As this is pro version it is required more effort to set up your development environment, we suggest to use mstore-expo if you have not familiar with React Native framework.

**Comment by kaledjeff** [comment]
I need the pro version for RTL and push notification. Is there a way to add that to the Expo version?

Do you I need mac to build an ios application?

**Comment by inspireui** [comment]
Hi sorry for lated response on this ticket, regarding to the RTL on Expo version it will be have some limit as it is not support completely to modify the native setting on Xcode or Android Studio so we suggest to use RTL on Pro version (your can refer to this document for the detail config - https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html)

The push notification is ok but you need to make the dashboard backend to support push the message like OneSignal. Thank you!
