### ISSUE TITLE
BeoNews Expo Integration DOES NOT work

### ISSUE THREAD

**Issue by raymondzb** [inspireui/mstore#68]
My purchase code is:

3fa55ee9-4eab-4612-b32f-11e100c23f46

I bought this through CodeCanyon.  I tried to follow your instructions here:

https://beonews.inspireui.com/test2.html

but the Expo documentation simply does  not work and is of no help!  This was supposed to be Expo integrated out of the box.  It is not.

Furthermore, the Pro version instructions are unclear.  At one point, you show a link to a Youtube video that is blurry and has no sound.

I am about to hit CodeCanyon with a chargeback and report this as a fraudulent product.

**Comment by inspireui** [comment]
You can try the guide for Expo at this guide - https://beonews.inspireui.com/version-24.html

Thanks.
