### ISSUE TITLE
Issue 3.1

### ISSUE THREAD

**Issue by wphjaelpen** [inspireui/mstore#7]
1) All order made with the Mstore Expo app, just show 0.00 in the Woocommerce backend.

2)
The thumbnail first show up on the product page when you tap the screen: See screenshot https://cl.ly/2a2a270P1n0A

**Comment by inspireui** [comment]
Thank you, we will check and update it shortly with the stock management issue

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 are fixed these issues. Please help to open new ticket if there are still issues. Thank you so much for your feedback
