### ISSUE TITLE
Retains the products in the shopping cart after the purchase

### ISSUE THREAD

**Issue by mustymx** [inspireui/mstore#71]
Even 3.3.3 retains the products in the shopping cart after the purchase.
After shopping the shopping cart must be emptied
<a href="https://imgur.com/TOac2Yk"><img src="https://i.imgur.com/TOac2Yk.png" title="source: imgur.com" /></a>

**Comment by inspireui** [comment]
We could not replicate this issue on the demo http://expo.io/@minhcasi/mstore, could you help to clarify more? Thank you!

**Comment by inspireui** [comment]
Thank you, we will review it again and do investigate it deeply.

**Comment by mv-developer** [comment]
Hello, 
I have the same issues i create custom payment type.

**Comment by inspireui** [comment]
Fixed on v3.4.2
