### ISSUE TITLE
chnage to RTL error 

### ISSUE THREAD

**Issue by mgolkardev** [inspireui/mstore#72]
Hi
I have a bug.
Please watch the video.

https://youtu.be/wKjDX78Rvew

Please fix the bug.

**Comment by mgolkardev** [comment]
Hi
Can anyone help?
https://youtu.be/wKjDX78Rvew

**Comment by inspireui** [comment]
Hi sorry for lated response, could you clarify more about the bug ? is it an issue with showing content after you click on the RTL menu ? Is it happening on the demo app on Google Store or from your local setting ?

Thank you!

**Comment by mgolkardev** [comment]
Hi @inspireui
The previous vision (https://youtu.be/wKjDX78Rvew) was the local, but the video below is from the Play Store.

`mstore on Play Store : ` 
When right-to-left or reverse, the pages are not displayed until we close the app and open it.

**Comment by inspireui** [comment]
Hi thank you, this could be the issue RTL on Android, i've marked this as the bug and will review and update on next version.

**Comment by mgolkardev** [comment]
Hi
I'm waiting for your new update.
Thanks a lot

**Comment by mgolkardev** [comment]
Hi
I change `animationEnabled : true` and `lazy : true` in navigation/index.js and Bug fixed.
Let me know if there is another problem with my change.

```
        {
          tabBarComponent: TabBar,
          tabBarPosition: 'bottom',
          swipeEnabled: false,
          animationEnabled: false => true,
          tabBarOptions: {
            showIcon: true,
            showLabel: true,
            activeTintColor: Color.tabbarTint,
            inactiveTintColor: Color.tabbarColor,
            // style: {
            //   backgroundColor: Color.tabbar,
            // },
          },
          lazy: false => true
```

**Comment by inspireui** [comment]
Hi, it's correct updated. 

There are some minors issues on RTL and we will update it on v3.4 on next couple of days. Thank you!

**Comment by mgolkardev** [comment]
Hi

Thank you for your amazing update!
Many problems were solved.
But there's a big problem.
When the default is `RTL = True in Constants.js` and I install the app, app is LTR until I close the app and reopen it.

I,m waiting for your response.

**Comment by inspireui** [comment]
Hi the RTL option can be change dynamic from Pro version (the setting option from left side bar).

The option from Constants.js is used for persist at the first loading app, it mean it will RTL if the first time user open the app. You can try to test this feature by Earse the content and Setting data from simulator, then install the app again.

Thank you!

**Comment by mgolkardev** [comment]
Hi

The problem is resolved when i change RTL in settings.
The main problem is that when in `Constants.js RTL = true`, the display still LTR for the first time the app is installed and opened. Note: **this is only for the first installation, and the first time the program opens**, this is a problem.

I hope to achieve a stable version by fixing the current issues.

Thanks a lot

**Comment by inspireui** [comment]
Hi, i've sent this issue to technical for investigate further and have a fix if he can replicate the issues. Thank you!

**Comment by mgolkardev** [comment]
Hi @inspireu
Thank you for 3.4.4 release.
I update my project to 3.4.4 version but `RTL bug in first run` not fixed!

Please watch this video:
https://youtu.be/n4H04dnUeDU

Thank you for your support.
