### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by masoudkhademi** [inspireui/mstore#74]
when users register in app . they use an email but maybe this email is not their email and it . this may cause security problems . users must confirm their email to activate their account .how can i do it?

**Comment by inspireui** [comment]
Hi you can upgrade the registration flow base on your business, you could update your wordpress site to prevent user sing up from the app if he is not activate the email.

The app is also checking unique email when process registration via Rest API.

Btw, it's flexible to update the code base on your business.
