### ISSUE TITLE
how set the HorizonLayout i can't set it  

### ISSUE THREAD

**Issue by xa9** [inspireui/mstore#75]
i can't understand the : https://mstore.gitbooks.io/mstore-manual/content/chapter6.html

and set the HorizonLayout in home page .

tag ,category and name

**Comment by inspireui** [comment]
Hi this is used for config the horizontal layout from the homepage, it is quite dynamic by this config as you can add the flexible homepage. Please try to change the category id or tag id that match with your Wordpress site then it will appear on the app. Thank you!
