### ISSUE TITLE
there is no clean and rebuild option in my android studio(2.3) for this project. 

### ISSUE THREAD

**Issue by hitomtao** [inspireui/mstore#76]
there is no clean and rebuild option in my android studio(2.3) for this project. 
and following the windows install video guide, failed at last, app in android notice unable to load script from assets 'index.android.bundle' ...

**Comment by inspireui** [comment]
Hi,

Could you make sure your Android SDK config correctly base on this guide - https://goo.gl/Fmcsf1

Then you can run this cmd to build the app on Android:
yarn start
react-native run-android 

Or it can also build by Android Studio (please don't upgrade the grade version from the project.

Please also try with out video installing guide on both ios or Window OS
