### ISSUE TITLE
Urgent Bug in display products for specific categories

### ISSUE THREAD

**Issue by 4ship** [inspireui/mstore#77]
In home page there are many categories, I tried to display products  for specific categories in each section but always show only one category for all sections.

I checked the code , WoocommerceAPI was sending only URL without data. I had to do this to fix it

```
if (method == 'GET') {
        params.headers = {'Cache-Control': 'no-cache'};
        params.url = params.url + this.join(data, '&');
}
```

hope this help

**Comment by minhcasi** [comment]
Thank you so much for your suggestion, this issue on happing on https, we will update the fixed on next version together with some extra feature like shipping and coupon...

**Comment by inspireui** [comment]
i'm closing this ticket as this will be updated on 3.4.
