### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by mv-developer** [inspireui/mstore#79]
Hello, 
Item Purchase Code: 201fa5ca-0107-44dd-8738-8fdb46bc9c8f
When i run : react-native run-ios i have this error message

BUILD FAILED **
The following commands produced analyzer issues: Analyze /Users/ahmedwali/Projects/ReactNative/mstore-v3.3.3/mstore-pro/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c Analyze /Users/ahmedwali/Projects/ReactNative/mstore-v3.3.3/mstore-pro/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c (2 commands with analyzer issues)

The following build commands failed: CompileC /Users/ahmedwali/Projects/ReactNative/mstore-v3.3.3/mstore-pro/ios/build/Build/Intermediates.noindex/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSCardFieldManager.o TPSStripe/TPSCardFieldManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2): Failed to install the requested application An application bundle was not found at the provided path. Provide a valid path to the desired application bundle. Print: Entry, ”:CFBundleIdentifier, Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist Print: Entry,”, Does Not Exis

**Comment by minhcasi** [comment]
Please try to install this library again - https://github.com/tipsi/tipsi-stripe 

Then run: react-native link

It will fixed this issues.
