### ISSUE TITLE
Installation help, 2 questions.

### ISSUE THREAD

**Issue by LuisJorgeAr** [inspireui/mstore#8]
Hi all,

1. Upon buying it on CodeCanyon, you will be able to download the zip file that contains the complete app template. After you unzip it, you'll need to change to the template folder in your shell and run npm install to fetch all dependencies.

Luis: after running command "npm install" got the following 3 message (at the end), is this correct?

── babel-plugin-transform-remove-console@6.8.4 
├── base-64@0.1.0 
├── bluebird@3.5.0 
.....
.....
methods@1.1.2 
    └── qs@6.5.0 

npm WARN react-native-swipe-list-view@0.4.1 requires a peer of react@>=0.14.8 but none was installed.
npm WARN react-native-render-html@2.0.0 requires a peer of react@>=16.0.0-alpha.26 but none was installed.
npm WARN react-native-google-signin@0.10.0 requires a peer of react@>=15.4.0 but none was installed.

2. After sucessfully executing "chmod +x android/gradlem"
Tried to run "react-native run-android" but got the following message:
-bash: react-native: command not found

Can you help?

Thanks

**Comment by alien3d** [comment]
have you install react-native via npm ?
npm install react-native 
** i buy just now but still can't work on windows. Later at home i try using mac can or not

**Comment by inspireui** [comment]
Hi LuisJorgeAr, please try to install the react-native-cli by this cmd:  npm install react-native-cli -g

**Comment by LuisJorgeAr** [comment]
Hi inspireui,

Tried the command you indicated "npm install react-native-cli -g". However, I am still getting errors, please see the log below:

luis$ npm install react-native-cli -g
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-cli" "-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path ../lib/node_modules/react-native-cli/index.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/react-native-cli/index.js' -> '/usr/local/bin/react-native'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../lib/node_modules/react-native-cli/index.js' -> '/usr/local/bin/react-native'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/react-native-cli/index.js',
npm ERR!   dest: '/usr/local/bin/react-native' }

I also tried alien3d's suggestion by running "npm install react-native", but got some missing data, as shown here:

luis$ npm install react-native
mstore-expo@ /Users/luis/Documents/AppOnlineStore/MStore_v3.1/mstore.3.1/mstore-pro
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.12
└── react-native@0.45.1 

npm WARN react-native-google-signin@0.10.0 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-render-html@2.0.0 requires a peer of react@>=16.0.0-alpha.26 but none was installed.
npm WARN react-native-swipe-list-view@0.4.1 requires a peer of react@>=0.14.8 but none was installed.

Please help with the installation process, it is not smoothly or there is a lack of information about troubleshooting to users.

Thanks

**Comment by alien3d** [comment]
-g for global  ..   yes  i get the same error .. 
after your do that then react-native link and react-native run-android or react-native run-ios
I'm still struggle on windows site on mac site still got error..i will post rtf what i done .. in a link wait ya

**Comment by alien3d** [comment]
you may check at https://facebook.github.io/react-native/docs/getting-started.html
click tab  building project with native code

**Comment by inspireui** [comment]
Close and link to the issues which happen on Window OS #15
