### ISSUE TITLE
A bug blocking us before launching

### ISSUE THREAD

**Issue by emreaky** [inspireui/mstore#80]
We have a critical bug that blocking us before launch. in our app every category shows same products also when we scroll the list products duplicated again and again. On homepage it shows same products again. Can you help us to solve this problem.

**Comment by amineprogram** [comment]
Are you using https ? if yes this is a bug just use http

**Comment by emreaky** [comment]
Yes we are using https when will you fix this issue? We must use https because of security.

**Comment by inspireui** [comment]
Hi @emreaky, could you try to replace this file on the project https://github.com/minhcasi/react-native-woocommerce/blob/master/WooCommerceAPI.js it will fix the http issues. 

If you are still trouble with the issue after replaced this file, please share your constants and config file to our support email: support@inspireui.com We will help to investigate further and fix it. 
Thank you!

**Comment by inspireui** [comment]
this will be fixed on v3.4 which will be ready in 1-2 days.
