### ISSUE TITLE
unable to add featured products to homepage

### ISSUE THREAD

**Issue by mtx62** [inspireui/mstore#81]
Greetings,
It's not mentioned in the documentation how to add featured products to homepage
Best regards.

**Comment by mtx62** [comment]
Dear, I think you need to update the code,
because I changed tag to tags and it's working now.

**Comment by lwincmm** [comment]
hi mtx62,
How did you do it ?
I am interested featured ad.
rgds

**Comment by mtx62** [comment]
If you looking for a quick answer but it's not professional way then,
open `src/services/WooWorker.js` and go to line 69 and change
`params = {...params, tag }`
to
`params = {...params, tags: tag }`
and you are done.

**Comment by inspireui** [comment]
Hi @lwincmm please refer to the guide from https://mstore.gitbooks.io/mstore-manual/content/chapter6.html "Change the HomePage horizontal layout" Thank you!

Thanks @mtx62 we will have a check the tag issue on WooWorker

**Comment by inspireui** [comment]
Fixed on 3.4, it will be ready in 1-2 days.
