### ISSUE TITLE
Urgent mstore error : null is not an object (evaluating category.image.src)

### ISSUE THREAD

**Issue by amineprogram** [inspireui/mstore#82]
We have a critical new bug that crash the app 
error :  https://imgur.com/a/EyCGx  
video recorder : https://drive.google.com/file/d/1RIPEcGCpUcw5cLNBRPNfVdfn1aOkSaW6/view?usp=sharing
i have the error with original config and with my config

**Comment by inspireui** [comment]
Hi, please go to the WooCommerce product category and update the banner - https://gyazo.com/a101cc15a50f3a83d3f6b7f8bcedc00f  - it will fix the issues. Thank you!

**Comment by amineprogram** [comment]
thanks problem resolved 👍
Waiting the new release
