### ISSUE TITLE
amazon affiliate sales

### ISSUE THREAD

**Issue by tohapiliang** [inspireui/mstore#84]
PreSales, this app work with amazon affiliate sales, when click order can open the amazone app or open Browser Web View int the app ?

Please Reply Thankyou!

**Comment by inspireui** [comment]
Yes, it's possible, you can customize by adding the "In-App Browsers" feature that support to open the  right on the app with you affiliate sales. Could you provide some detail about the affiliate link or website that we can help to check the solution for you. Thank you!

**Comment by simoricu** [comment]
Hi, I've the same needs. Can you check my website here: https://www.guidacani.it/ (homepage) and https://www.guidacani.it/shop (shop).
Can you give me a feedback about compatibility with your template?
Thank you

**Comment by Brdnn** [comment]
Looking forward for this features too!

**Comment by inspireui** [comment]
Noted, please move to https://inspireui.ticksy.com/ - Thank you !
