### ISSUE TITLE
following instructions for building on iOS, build failing with the following error

### ISSUE THREAD

**Issue by teodorboev** [inspireui/mstore#86]
following instructions for building on iOS, build failing with the following error
<img width="647" alt="screen shot 2017-11-28 at 14 47 56" src="https://user-images.githubusercontent.com/1229117/33325890-74e9bb46-d44b-11e7-9efe-d5eba9052641.png">

File is the in the folder!

Please advice!?

pcode:  2c6b0992-197a-4870-8091-45295263b367

**Comment by minhcasi** [comment]
For iOS, you need to download the FacebookSDK(https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip) and copy to ~/Documents/FacebookSDK.

https://mstore.gitbooks.io/mstore-manual/content/chapter1.html

**Comment by inspireui** [comment]
Hi, kindly reopen this ticket if the solution is not worked. Thank you!
