### ISSUE TITLE
Images not loading in app

### ISSUE THREAD

**Issue by JKLTechno** [inspireui/mstore#87]
app working perfectly but images not loading from site to app.

**Comment by minhcasi** [comment]
Hi, please check the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html

 and the horizontal layout config from - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html

**Comment by eric90066** [comment]
I am seeing the same thing.   Only 5-10 images.

**Comment by jigar990** [comment]
app working perfectly but if i add new product images not loading plz help me out and how to change currency

**Comment by inspireui** [comment]
HI @JKLTechno @eric90066 how is your checking with latest v4.3.2 Could i close this ticket if already resolved ?

**Comment by SantiMancini** [comment]
I'm having this problem too. Any way of solving this?

**Comment by inspireui** [comment]
Hi @SantiMancini what's the version that you are using, if you are using v3.4.2 please follow the step from config.js file to correct the images issue Thank you!

**Comment by SantiMancini** [comment]
@inspireui Fixed with version 3.4.2. Thanks. I have some new problems with Product Description in this new version (bad rendering issues). I will open a new issue if I can't fix it by myself.
Thanks again!

**Comment by inspireui** [comment]
[index.js.zip](https://github.com/inspireui/mstore/files/1566479/index.js.zip)

Could you try to override this file to containers/Detail/ folder to see if it can be fix the description issue, or you can remove the tag "p" at the HTMLView from that file - https://gyazo.com/3b4986f0df98d7f1a8f0cf43a03bc24c

Let us know your checking, thank you! We are updating new version to fix these issue.
