### ISSUE TITLE
installation..

### ISSUE THREAD

**Issue by alien3d** [inspireui/mstore#9]
1. i try using npm and yarn install  for android 6.0  keep complain   dex something
2, i try using android 7.0  couldn't delete path  dex\debug\folders\1000\1f

I cannot download the wordpress.. 
Forbidden
Can't access this page

**Comment by inspireui** [comment]
Hi, could you check  your SDK is update the latest and make sure Extra/ Android Support Repository, Google Play Services, Google Repository and Intel x86... are installed like this guide:
https://github.com/devfd/react-native-google-signin/blob/master/android-guide.md

**Comment by alien3d** [comment]
yea.. been done that and react-native link ..  i will test in mac few hour.. i suspected long name issue.The problem was i'm using windows that time.

**Comment by inspireui** [comment]
Please try to rename the folder without space " ", there are some issue with RN 0.45 on Dex by the spacing folder naming.

**Comment by alien3d** [comment]
no space by now.. testing mac error
1. facebook sdk not in the document folder.. done.. okay
2. linker error.....   /Users/name/library/developer/xcode/deriveddata/beostore-sdfsdfsdf/Product/iphonesimulator directory not found..

**Comment by alien3d** [comment]
Is there any bullet prooved installation like video  in youtube? i'm pretty odd what version react u used  in the video

**Comment by alien3d** [comment]
using mac .final error mutiple dex files define. lcom/google/android/gms/iid/zzc

**Comment by alien3d** [comment]
confirm bugs  on windows stripe
https://github.com/tipsi/tipsi-stripe/issues/56

**Comment by inspireui** [comment]
Thank you, this could an issue of tipsi-stripe on Window, can i know your Window version and the Android SDK? We may consider to change the tipsi-stripe by 
Webview Stripe support. This is work well on Mac for both Android & iOS. In the mean time please disable this library and we will check solution to replace.

**Comment by alien3d** [comment]
Windows : Windows 10
Android SDK : i just download all em all and update all the latest. Only target 19 to 25 . 16 seem to low and rarely find people use kit kat..  26 android 8.. rather not waste space.
For now , coverage stripe not much i don't use.. For other maybe.

**Comment by alien3d** [comment]
![wordpress3](https://user-images.githubusercontent.com/222886/28236325-10080e2c-6956-11e7-8231-8758eb5e5804.png)
We need real database which host at expo or mstore.io not other..

**Comment by inspireui** [comment]
Hi, i'm closing this ticket as the new v3.2 are fixed all these installing issues. Please help to open new ticket or reopen it if there are still issues. Thank you so much for your feedback
