### ISSUE TITLE
App sync to woocommerce site incomplete

### ISSUE THREAD

**Issue by eric90066** [inspireui/mstore#90]
Using mstore-pro. 

No other way to describe this.  The app correctly displays the same ten or so items in my webstore through out the app. 

The home page is full of the same products.   When clicking on a product category selected for the home page, at the top I see template store items, and my items below.  

Also the product categories section appears to display the appropriate category images, but when you click on a category it is the same list of items as on the home page without any images only text.

Clearly there is an issue with the app syncing with woocommerce.  There are no error codes in the terminal.  

Also, it is unclear how to change the name of the store on the header or how to add or remove items from the product category list. 

Any help is appreciated.

**Comment by eric90066** [comment]
Since the app developer is missing in action - for the curious - I discovered the store name is an image and stored in the images folder (/src/images) under the name 'new_logo.png'.

**Comment by inspireui** [comment]
Hi @eric90066  confirmed that the categories issues will be fix on v3.4. Thank you!

**Comment by eric90066** [comment]
Hello - updated to new version.  Had to start from scratch since there are no instructions on how to upgrade. 

Received the following error during build:

Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:Execution failed for task ':react-native-fbsdk:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt


Please advise.

**Comment by inspireui** [comment]
Please download the latest v3.4.2 will fixed the keyboardNavigationCluster on Android

**Comment by eric90066** [comment]
The menu button and header appear to be missing on shopping cart, search and favorites pages. 

In addition there are two contact us buttons.  Is there a function to link to the contact us page on my website?

**Comment by eric90066** [comment]
3.4.2 appears to have fixed a lot of the issues.  The home page images come up without issue and I see the entire catalogue of items on that page. 

Some of the button images are missing such as the header (as mentioned above).  Where are those images stored?

For the product page some of the the images are missing or incomplete for a number of products.  I tried resizing the thumbs and they did not appear to work.  Also, I have pages with video in an iframe.  Does the app support iframe?
  
Meanwhile, the categories section is also missing images. ,

Also when rotating the phone, the app and the images are not responsive. Is that to be expected?

Please advise.

**Comment by eric90066** [comment]
Also, please advise how to control the size of images within a web page.  For instance, all my products display like this on webpage:

![2017-12-11 at 00-00-43](https://user-images.githubusercontent.com/5639308/33816513-6420b42a-de07-11e7-9687-3d4dfcf549d3.png)

And like this on the app

![screenshot 2017-12-11 00 05 46](https://user-images.githubusercontent.com/5639308/33816521-72389604-de07-11e7-8a1b-ef274191c584.png)

How to control the size of images within the webpage for use in the app?  What should the dimensions for the thumbs be?

**Comment by eric90066** [comment]
What might be ideal here is a function to block images, text, video and iframe in the body of the product page when using on a mobile device. 

I think this would have to be a wordpress plugin, no?

**Comment by inspireui** [comment]
Hi, you can modify the description content and remove some image from src/container/Detail/index.js, search the HTMLView which is render by react-native-render-html

You can also customize the style for each tag: https://github.com/archriss/react-native-render-html#creating-custom-renderers

**Comment by eric90066** [comment]
But I cannot see gallery images on product page.

In addition, for some pages I get this:

![screen shot 2017-12-12 at 1 51 03 pm](https://user-images.githubusercontent.com/5639308/33902700-dca076f0-df43-11e7-8479-f5ae448a8a11.png)

**Comment by eric90066** [comment]
And this:

![screen shot 2017-12-12 at 1 55 00 pm](https://user-images.githubusercontent.com/5639308/33902775-183a8f3e-df44-11e7-85ef-116ccc0a1691.png)

**Comment by eric90066** [comment]
Also, what I don't understand, products that appears perfectly on the home page, does not appear at all on the catalog page. 

There is an issue with the loading of images away from the home page.

**Comment by eric90066** [comment]
In addition, I don't understand why the "news" section does not work.   This was linked to my blog on 3.4.1.  On this version it does nothing.

**Comment by eric90066** [comment]
After running a clean and rebuild, this is what I am seeing on category page:

![screen shot 2017-12-12 at 4 36 36 pm](https://user-images.githubusercontent.com/5639308/33909869-fc05a3fa-df5a-11e7-93c0-5145c8be8b46.png)

**Comment by inspireui** [comment]
Could you share your website URL then we could have a look ?

**Comment by eric90066** [comment]
Sure. 

This is an example of one product page:

https://looksavebuy.com/shop/on-the-run/universal-air-vent-phone-cradle-for-smartphones/

**Comment by inspireui** [comment]
I see, could you share all package which already config on your site then send us via email - support@inspireui.com We will help to fix this issue then send back to you. Thank you!

**Comment by eric90066** [comment]
Email sent.

**Comment by eric90066** [comment]
This change has improved the app in android, but I cannot see all images or text for my products.  

Please advise.

**Comment by inspireui** [comment]
Hi, could you resend the image screenshot issues again so that we can check. Thank you!

**Comment by eric90066** [comment]
Here are images.   This one is the categories page.  Only one product displays: 

![screen shot 2017-12-19 at 11 30 12 pm](https://user-images.githubusercontent.com/5639308/34191408-c3ca44a4-e514-11e7-961b-9c7efb009cea.png)

This is a product page.  It is blank. 

![screen shot 2017-12-19 at 11 30 30 pm](https://user-images.githubusercontent.com/5639308/34191417-d3d106e4-e514-11e7-9b79-aa02735eb153.png)

This appeared when trying to view one product

![screen shot 2017-12-19 at 11 29 13 pm](https://user-images.githubusercontent.com/5639308/34191443-119a276c-e515-11e7-9f23-3109e1242872.png)

**Comment by inspireui** [comment]
Hi @eric90066 could you try to release the Look Save Buy website to the hosting instead of use from the local, as i know Android have some issue with the image loading from local, it will be fixed when it is online Please try to test it on iOS if it is the same or not Thank you!

**Comment by eric90066** [comment]
Hi inspireui, 

The looksavebuy website is hosted on a remote server.   The site is is not run locally.

**Comment by eric90066** [comment]
Running using iOS is better.  Product pages that do appear are complete.  But categories are still missing images and some products are still missing images. 

![screen shot 2017-12-22 at 12 19 48 pm](https://user-images.githubusercontent.com/5639308/34306847-4c2114b8-e713-11e7-8dbc-b0a4119420b0.png)

From the Xcode console the following errors:

![screen shot 2017-12-22 at 12 24 10 pm](https://user-images.githubusercontent.com/5639308/34306908-93e2f73a-e713-11e7-91c8-80156eee9f0a.png)

This error appears to be for the images in the body of the webpage for some products.  

![screen shot 2017-12-22 at 12 25 01 pm](https://user-images.githubusercontent.com/5639308/34306989-feb15200-e713-11e7-9cd1-88885bdf2784.png)

Finally, one product gives the following red screen of death in iOS

![screen shot 2017-12-22 at 12 26 58 pm](https://user-images.githubusercontent.com/5639308/34307003-0caa8a34-e714-11e7-94e9-213f5f0b87ef.png)

**Comment by eric90066** [comment]
Quick follow up.   Re ran the app in iPhone 8 plus (previous was in the 6s) and almost all products appeared with pictures (yeah!). 

Some images embed in the product page were not sized correctly to fit the page and in some cases had all images appear properly but was missing text (which was below the images).  

![screen shot 2017-12-22 at 1 04 14 pm](https://user-images.githubusercontent.com/5639308/34307938-ad3c489e-e718-11e7-8b50-0306c73b0344.png)



but I was excited to see iframe video and gallery images appeared for almost all products.  Great.  

But still the category list pages are blank.   How to fix?

![screen shot 2017-12-22 at 12 59 42 pm](https://user-images.githubusercontent.com/5639308/34307871-4cef6f48-e718-11e7-93ba-4159f9a54fe7.png)

**Comment by eric90066** [comment]
Any update to this issue?

**Comment by inspireui** [comment]
Hi @eric90066 , please check this issue with latest version v3.4.4 (on next 1-2 days), i believe it will be fix your cases. Thank you

**Comment by eric90066** [comment]
Sounds great.  Look forward to testing this out.  Cheers.

**Comment by eric90066** [comment]
This update has greatly improved the images issue.  Now I can begin testing other areas. 
Thanks for the work.
