### ISSUE TITLE
Demo launch problem

### ISSUE THREAD

**Issue by Vrijlating** [inspireui/mstore#92]
Hello,
i have a problem on launching the demo on my pc.
When I launch the code "react-native run-ios" appear this error: (image attach.)
<img width="429" alt="problem" src="https://user-images.githubusercontent.com/31366135/33713878-3650c88a-db4d-11e7-8f0a-9ff36a729a77.png">
I have also try to launch with " sudo react-native run-ios" but in this case don't open the simulator.
How I can solve it?

**Comment by Vrijlating** [comment]
Meanwhile I have retry to make the operations and there is these error:
`** BUILD FAILED **


The following build commands failed:
	CompileC /Users/darioditto/Desktop/mstore-pro/ios/build/Build/Intermediates.noindex/RCTOneSignal.build/Debug-iphonesimulator/RCTOneSignal.build/Objects-normal/x86_64/UNUserNotificationCenter+OneSignal.o OneSignalNativeSDK/OneSignal/UNUserNotificationCenter+OneSignal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/darioditto/Desktop/mstore-pro/ios/build/Build/Intermediates.noindex/RCTOneSignal.build/Debug-iphonesimulator/RCTOneSignal.build/Objects-normal/x86_64/NSString+OneSignal.o OneSignalNativeSDK/OneSignal/NSString+OneSignal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

	CompileC /Users/darioditto/Desktop/mstore-pro/ios/build/Build/Intermediates.noindex/RCTRestart.build/Debug-iphonesimulator/RCTRestart.build/Objects-normal/x86_64/RCTRestart.o RCTRestart/RCTRestart.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/darioditto/Desktop/mstore-pro/ios/build/Build/Intermediates.noindex/RCTText.build/Debug-iphonesimulator/RCTText.build/Objects-normal/x86_64/RCTTextManager.o RCTTextManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by inspireui** [comment]
Could you try with this script to clean the cache - https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9

**Comment by Vrijlating** [comment]
Appear this:
$ react-native run-ios
module.js:538
    throw err;
    ^

Error: Cannot find module './local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/darioditto/Desktop/mstore-pro/node_modules/react-native/cli.js:11:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by inspireui** [comment]
Hi, it looks like you have not install npm for the node library, please try to update to latest version - http://nodejs.org

Please try to install all required library base on this guide: 
https://facebook.github.io/react-native/docs/getting-started.html
https://mstore.gitbooks.io/mstore-manual
Or use this video for the set up - https://www.youtube.com/watch?v=XYsQcXTb_HA&t=4s

**Comment by inspireui** [comment]
Not sure you have fixed this issue, feel free to reopen it if you still have an issue. thank you!
