### ISSUE TITLE
Xcode problem

### ISSUE THREAD

**Issue by jafarnajafov** [inspireui/mstore#93]
mstore-pro/node_modules/react-native/Libraries/Vibration/RCTVibration.h:10:9: ‘React/RCTBridgeModule.h’ file not found

Purchase code: a6ea1135-dec9-4676-ae03-65a3849e3e64

![2017-12-08 10 40 58](https://user-images.githubusercontent.com/19730745/33754339-355ddcd4-dc05-11e7-903d-ee30fc958b2f.png)

**Comment by inspireui** [comment]
It looks like you xcode project could not get the React lib, please try to config same as this screenshot 
<img width="904" alt="screen shot 2017-12-08 at 10 19 57 pm" src="https://user-images.githubusercontent.com/29778334/33772105-0efb34cc-dc66-11e7-9678-d6584547943f.png">

or try to clean the cache https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9\

**Comment by inspireui** [comment]
If you have not installed by above solution, please kindly reopen this ticket. Thank you!
