### ISSUE TITLE
Android Studio 2 error(s) and 1 warning

### ISSUE THREAD

**Issue by diryux** [inspireui/mstore#94]
I've got 2 errors while building the android app using android studio, any help would be appreciated

Purchase code: a218bcdf-e9be-4e31-9497-c2260b2965af

> Error:Failed to crunch file D:\work\apps\mstore-pro\node_modules\react-native-onesignal\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into D:\work\apps\neatmeat\mstore-pro\node_modules\react-native-onesignal\android\build\intermediates\res\merged\androidTest\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

> Error:Execution failed for task ':react-native-onesignal:mergeDebugAndroidTestResources'.
 Error: Failed to crunch file D:\work\apps\mstore-pro\node_modules\react-native-onesignal\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into D:\work\apps\neatmeat\mstore-pro\node_modules\react-native-onesignal\android\build\intermediates\res\merged\androidTest\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

and 1 warning which is: 

> Warning:AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

**Comment by inspireui** [comment]
Hi, could you download the latest v3.4.2 to see if it can be fixed this issues, thanks

**Comment by diryux** [comment]
Fixed it thanks
