### ISSUE TITLE
Error on Xcode

### ISSUE THREAD

**Issue by luisalexhg** [inspireui/mstore#95]
mstore-pro/node_modules/react-native/Libraries/Network/RCTNetworkTask.m:10:9: 'React/RCTLog.h' file not found

Purchase code: 993e4b07-50d6-4861-a282-c580c19a685e

![captura de pantalla 2017-12-08 a las 03 04 35](https://user-images.githubusercontent.com/28818275/33756852-5d1758f8-dbc5-11e7-9964-1f003a34abf6.png)

Please help!

**Comment by inspireui** [comment]
Hi, sorry i missed this ticket, please help to use solution on this ticket - https://github.com/inspireui/mstore/issues/93 or try to clean the cache and reinstall the libraries by using this script: https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9

**Comment by luisalexhg** [comment]
I have 1 month with the product and it don't work. I just did that but it does not work, also I already configured as indicated by the image but nothing.

iOS issues:
1. File not found.
![captura de pantalla 2017-12-13 a las 00 13 16](https://user-images.githubusercontent.com/28818275/33922719-9f6264c2-df9a-11e7-8c3b-ae473fd2e6ac.png)
- The configuration is ready 
![captura de pantalla 2017-12-13 a las 00 13 52](https://user-images.githubusercontent.com/28818275/33922724-aa1a017c-df9a-11e7-97e9-cf61959b13e9.png)

**Comment by inspireui** [comment]
Could you try with the latest version v3.4.2 which is release on last few days. If it's still un-succesful we can help with the remote support. Thanks

**Comment by luisalexhg** [comment]
I appreciate it immensely could help me in that way, I'll wait, thank you

**Comment by inspireui** [comment]
Okie, please send your team viewer to our support email support@inspireui.com then we will online on next 1h for the checking. Thank you!

**Comment by luisalexhg** [comment]
Ok, I already sent it. I will be online.

**Comment by luisalexhg** [comment]
I send u again the access

**Comment by inspireui** [comment]
Fixed by https://mstore.gitbooks.io/mstore-manual/chapter7.html
