### ISSUE TITLE
Error when bundling

### ISSUE THREAD

**Issue by karim-aly** [inspireui/mstore#96]
> error: bundling failed: SyntaxError in D:\Work\React\ReactNativeWorkspace\Kamkilo\src\common\Config.js: D:/Work/React/ReactNativeWorkspace/Kamkilo/src/common/Config.js: Unexpected token, expected , (50:16)
  48 |   Payments: {
  49 |     bacs: require('@images/payment_logo/PayPal.png'),
  50 |     cod: require('@images/payment_logo/cash_on_delivery.png'),
     |                        ^
  51 |     paypal: require('@images/payment_logo/PayPal.png'),
  52 |     stripe: require('@images/payment_logo/stripe.png'),
  53 |   },

**Comment by minhcasi** [comment]
Hi, it looks like you modify the config but your require image it not correctly, it should be like this require('@images/payment_logo/PayPal.png')...

<img width="579" alt="screen shot 2017-12-12 at 5 29 36 am" src="https://user-images.githubusercontent.com/1459805/33857303-b404bf1c-defd-11e7-8a7a-4830a6021b48.png">
