### ISSUE TITLE
new product images not loading

### ISSUE THREAD

**Issue by jigar990** [inspireui/mstore#97]
app working perfectly but if i add new product images not loading plz help me out and how to change currency

**Comment by minhcasi** [comment]
it could be cause by the cache for the offline feature, you can try to pull to refresh then it will load again, there is the currencyFormatter from src/Omni.js to change the symbol, we will update this for easier to config on next version. Thank you!

**Comment by inspireui** [comment]
Duplicate - https://github.com/inspireui/mstore/issues/87
