### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by martinledjo** [inspireui/mstore#98]
I can run the app with react-native run-ios
I have many error with RTC*
at the beginning i could not run with xcode either because of RTC error
so I added the library react in scheme
when i run i can't logout - i can't go on news
Screen:
http://image.noelshack.com/fichiers/2017/49/7/1512903002-unknown2.png

when i click on news nothing happen
i can logn in but when i disconnect it takes me on the connection as i was not connected
I need to restart the application so that I can press Logout
I did not have a problem in 3.3
but now I have too much bug

**Comment by martinledjo** [comment]
Purchase code: 71fce291-9906-4858-954e-9e1b6dca3688

**Comment by minhcasi** [comment]
Hi, could we check if you have customize the app already or use from the fresh download package, could you have a check from Xcode log to see what is the detail error when click to the news ?

You can try to reset the Content and Setting data from simulator from Hardware menu, the app is using from offline storage so it could cause this issues. 

Let us know your checking, thank you!

**Comment by inspireui** [comment]
How is you checking? If you still have an issues with the login please send your package to our support email support@inspireui.com Please note the v3.4.2 have fixed a lot of issues if you have modify the app you may need to merge code again. Thank you!
