### ISSUE TITLE
Multilingual Content

### ISSUE THREAD

**Issue by diryux** [inspireui/mstore#99]
Hey

I'm doing a multilingual app but I have a problem configuring it, whenever I change the language in the inside the app the products appear only in 1 language which I'm setting in config.js file.

I don't know how to sync both languages even when I added the second language

`const Constants = {
  RTL: true,
  Language: ['English','Arabic'],`

Thanks

**Comment by inspireui** [comment]
Hi, you can add more language from the common/Languages.js file, then it will be shown from the list automatically - https://gyazo.com/c0fe7a6992a3d56db2a00e5e1eac86c0
